#+STYLE: <link rel="stylesheet" type="text/css" href="./inc/css.css" /> 
#+TITLE: 本土PE的10条准则

#+BEGIN_HTML
<!--#include file="header.htm" -->
#+END_HTML

#+BEGIN_VERSE
PE投资始终是有技巧的，而经验的积累和感悟在投资中也非常重要。

投资经理在国内做PE，除了要掌握投资技巧外，我觉得还得具有以下10种能力：1.专业能力；2.企业家思维；3.熟谙资本市场；4.良好的沟通能力；5.自信心与火候；6.坚持、执著；7.大气的社交能力；8.拥有资源；9.擅长一项运动；10.性情中人，该喝时能喝。

这10种能力和素质，其内在缘由需要细细体会。能力越全，说明素质越好，发展空间越大。立志从事PE，或者做优秀投资经理的，可参照10种能力进行自我提高。
 
PE投资的10条准则

每天看《新闻联播》的意义何在，PE如何为管理团队相面，如何判断项目的投资价值？总结10年投资经验而得的PE投资基本准则，或对提高新晋PE的投资效率有所帮助。
　　
2009年再次掀起的PE热潮，不仅点燃了LP们投资PE的热情，也让GP队伍迅速扩容。从券商直投等正规军，到几个人临时组建的新班子，各路人马纷纷涌入，摇身一变成为GP。其结果是，PE行业的乱象不断为人诟病。
　　
对于GP而言，是在PE浪潮中裸泳，还是将其打造成持久的事业；是追逐项目快速IPO带来资本市场红利的刺激，还是悉心培育自身的核心竞争力，值得深思。将军赶路，不追小兔，提炼和实践PE投资的一些基本准则，对提高PE投资的效率、避免所谓的PE乱象，也许会有一些帮助。

1.每天都看《新闻联播》，听党的话，跟党走

看《新闻联播》，其实就是理解和跟踪国家的政策走向。国家政策的每一次调整，既可能催生很多很好的新投资机会，也可能对一些投资领域产生重大的不利影响。比如，新能源行业一直受到国家扶持，这几年也涌现了众多优秀的公司，但是其中的太阳能和风能领域的简单制造业产能过剩，受到政策限制。可见，即使在新能源行业，由于政策导向不一样，发展的机会不一样，投资方向也就不一样。
　　
在国家鼓励发展的行业中，一定存在着众多的投资机会；而在限制发展的行业，即使再努力，也无法突破已然存在的天花板。例如，这两年的房地产市场就像2008年中国6 000多点的股市，如果无视政府对房价的严厉调控，继续看涨这个行业，投资可能就面临风险。
　　
学习和掌握国家的政策，除了关注产业政策外，还有一个重要的方面，那就是对国内外资本市场要有前瞻性的研究。资本市场对PE投资的方向和退出都有很重要的影响，几乎每一次PE行业步入低谷都由股市的深度调整引发，中小板、创业板对PE的带动则是另一个例证。只有跟踪政策的走向，把握未来的趋势，PE才能规避系统性风险，获得良好的回报。

2.先选赛道，再选选手，在熟悉的领域作投资
　　
目前本土PE与外资PE一个重要的差异，就是专业化程度的区别。本土PE的泛投资现象比比皆是，只要是启动上市程序的Pre-IPO项目，就会被各种本土PE追逐，攀比价格和关系。而长期来看，只凭会计报表的数字判断项目企业的价值、凭中介机构的态度进行投资的时代终将过去，PE未来的竞争是专业化的竞争。
　　
PE要成为一个专业的投资机构，首先要关注自己熟悉的领域，在把握行业大方向的基础上，对细分行业作进一步的了解，筛选出高速成长、市场空间巨大的重点投资领域。对于一些专业性比较强的领域，比如生物制药，即使行业成长性再好，如果缺乏熟悉这一领域的GP，投资起来也会非常吃力。因此，围绕熟悉的领域作投资，并培养专业人才，积累专业经验，才会更好地理解行业，从中找到好的投资对象。
　　
对于本土PE而言，结合自身的特点，培养和提高自己的专业投资能力，并形成专业性投资基金，才是未来的发展方向。

3.成长性是投资的核心标准
　　
投资本质上就是投资未来，只有项目具备良好的持续成长性，投资才能成功。虽然企业的投资标准包含很多内容，但成长性始终是核心。
　　
对被投企业而言，创新是本质，成长是结果，因此，考察其成长性，关键在于寻找支持其持续成长的核心能力。企业的核心能力可以表现在品牌、技术、管理、文化等很多方面。对于技术型企业，是否拥有持续的技术创新能力、研发人员和技术创新体系，是判断其成长性的关键。对于运营型企业，是否拥有一支完整的、执行力高的团队是关键。而无论哪种因素是关键，企业的成长最终都会表现在财务等指标上，因此，千万不要被项目企业所谓的专利技术优势、名目繁多的奖状、资产规模及政府的重视程度等光环所迷惑，而最终要在核心能力和财务指标上找到成长的依据，以提升项目判断的可靠性。

4.注重市场应胜于注重技术

对于企业而言，技术并不一定等于专利，也不一定等于市场。判断技术的投资价值，不在于其高精尖程度，而在于其区别于传统技术的创新性、难以复制的独占性、带来成本下降或性能提高的赢利性以及创新能力的持续性，其核心就是能否带来市场占有率的持续成长。
　　
很多高科技企业，追求技术完美主义，沉迷于自己的技术，而忽略了市场对其技术的检验，不仅错失市场机会，也可能偏离市场所要求的方向。获奖级别越高的项目，往往投资的可能性越低，说的就是这种情况。因此，在考察企业时，市场往往比技术更重要，只有企业的市场有巨大的发展空间，其技术又能支持这样的市场目标，企业才真正有发展的潜力。

5.没有完美无缺的企业，重要的是找到改善企业的方法
　　
没有完美的企业，中国的中小企业，特别是民营企业，几乎每一家或多或少都存在诸如规范、纳税、管理、财务等方面的问题。对PE而言，企业不能改变只能改善。在投资的时候，关键不是寻找完美无缺的企业，而是针对企业已经存在的问题，看能否找到有效的解决办法，从而让企业得到改进和完善。比如，有些企业的商业模式会制约其发展，PE的作用就在于能否找到商业模式改进的方向，从而打开其未来发展的空间；有的企业技术能力很强、市场前景很好，但缺乏好的市场团队，PE此时的作用就在于为其找到合适的市场总监。从这一角度看，有改善潜质的企业应该受到关注。
　　
而有一些问题则可能是企业的硬伤，难以改变，这些企业可能就不适合投资。比如，核心团队或实际控制人存在问题，通过持续的沟通和影响但没有改进效果，PE就只有放弃投资。
　　
专业性的PE机构要有一系列帮助企业改善的方法，如通过建立"三会"制度提升其治理水平，通过"纳税"规范其发展，通过"股改"奠定其作为公众公司的基础，把企业变成健康成长的好孩子。

6.除了有钱，还要找一个说服项目方的理由
　　
PE投资时，经常会碰到这样的情况，几家PE同时要投资一个项目，项目方这时提出的问题往往是"除了钱，你还能为我做什么"。对PE而言，提供钱之外的价值才能构建自己的差异化优势，而这种优势往往成为投资的关键。
　　
除了钱之外，PE的价值可能是为项目方提供市场、人才等资源，或是在战略和管理上提供帮助，或是提供行业整合的机会。随着市场的成熟，尤其是项目方的成熟，PE"以钱制胜"的模式不断发生改变，钱之外的价值越来越重要。因此，构建自己的服务体系，为项目方提供额外的价值，将成为PE的一个重要竞争力。

7.懂得企业经营比懂得企业上市更重要
　　
国内资本市场目前存在一个现象：只要企业能上市，对其投资就一定有收益。不需要牌照，也不需要特别的能力，PE只要投资Pre-IPO项目，一级和二级市场的差价就能为其带来相对丰厚的资本市场红利。其实，经营才是企业的本质，IPO则是水到渠成。即使是现在，Pre-IPO项目也存在上市的不确定性，并且收益在不断波动；而随着资本市场的发展，这种简单的红利未来也许不复存在。返回企业的经营本质，才是判断企业投资价值的真正方法。

8.学会相面术，90%的企业出问题都是管理团队有问题
　　
项目投资后，由于各种条件不断变化，一些企业难免会出现各种问题，但那些最终影响企业生存的问题，90%以 上都和管理团队紧密相关。对于市场、技术等外部条件变化导致的问题，如果管理团队强，一般都能主动作出调整，从而保证企业持续发展。一个例证是，一家企业 曾因传呼业务萎缩而举步维艰，但在管理团队的带领下，最终成功向移动通信方向转型。而如果是祸起萧墙，则容易给企业带来致命的伤害。
　　
投资在于投人，PE在投资前要高度关注管理团队，作好调查。即使是夫妻店，也要了解其婚姻的稳定性。投资后更要密切关注管理团队在心态、内部管理等方面的变化，持续引导、教育、规范创业者，防微杜渐，才能有效遏制风险。

9.要想走得长远，就要保持谨慎
　　
PE行业最近10年的不断洗牌，与各家机构的投资理念和决策变化紧密相关。国内PE与外资PE有很大的不同，一是资金规模偏小，持续融资能力弱；二是投资组合对投资的成功率要求高。如果失败项目多，或者重要的项目投资失败，往往会对PE产生致命的打击。宁可错过，不能错投，虽然这有点绝对，却是PE生存的不二法则。错过几个项目，未来还有机会，可是如果投资了几个失败的项目，PE生存就存在问题了。因此，PE要在行业高潮和低谷的轮回中走得长远，就要始终保持谨慎的态度，在企业调研上，既要挖掘项目的价值，也要充分发现潜在的风险，坚决不作"赌博性投资"，尤其在行业一片乐观的情况下更应小心。

10.把合作变成习惯，联合投资是一种省力的方法
　　
一直以来，PE在投资金额比较大的项目时，往往会采用联合投资的方式，以规避基金对单一投资项目比例的限制或分散投资风险。如今，联合投资越来越多地被PE主动采用。
　　
从实际效果看，联合投资有助于PE在行业竞争加剧的形势下实现共享资源、共同发展。不同的PE，特色不同，资源和服务能力也不尽相同，联合投资后，PE可以整合彼此的力量，通过利用彼此的项目网络、专业经验等资源，扩大项目来源，提高投资效率，并为项目提供更多的增值服务。同洲电子当初正因为有深圳创新投、达晨创投等多家机构联合投资，它们以各自的资源为其提供服务，才获得持续发展并成功上市。
　　
PE的投资准则和理念固然重要，然而知易行难，更重要的是实践。PE只有精心努力，持续提升，做到心手合一，这十大准则才能真正发挥出作用。

9个数字决定投资成败

有经验的私募投资者如何进行审慎调查，他们会选择什么样的投资对象，9点经验之谈，不仅对于同行有借鉴意义，对于希望获取投资的企业经营者更是一份有益的参考。
　　
A企业技术领先、市场需求广阔，但管理团队经常变换，你投还是不投？B企业每年业绩增长50%以上，但在行业中排名并不居前列，你投还是不投？C企业财务指标看起来不错，产品具有竞争优势，但从来没给员工购买过社保，你投还是不投？PE或VC机构的专业投资者，总要面对这样的选择题。
　　
要发现待投企业潜在的未来价值和问题所在，除了研究企业的商业计划书（Business Plan，BP）之外，投资机构依靠的主要方法就是审慎调查。不同的机构、不同的投资人做审慎调查都有独门心法，而一套好的审慎调查策略和步骤无疑有助于投资人沙里淘金，慧眼识珠。在考察企业时，987654321这9个数字，凝聚了我们多年以来行之有效的审慎调查方法。

见过90%以上的股东和管理层

投资机构在与项目企业股东洽谈时容易犯的一个错误就是只和企业的实际控制人接触，而忽略了与小股东沟通。事实上，有时候与实际控制人以外的其他股东，特别是小股东进行的访谈，往往会起到意想不到的作用。在对前述企业小股东的访谈中我们就发现，A企业的6个股东中有3个小股东都反映，公司成立6年来，大股东近3年都没有开过股东会，而且存在不经过股东同意就对外担保事宜，这反映了公司的治理结构存在问题；B企业则存在股东名册以外的代持股东，我们由此提醒企业及时纠错，避免了今后IPO时的风险。
　　
与此相似的一个问题是投资者在走访项目企业管理层时，访谈的注意力只集中于公司董事长、总经理或其他与企业经营直接相关的管理团队上，而忽略了公司内 诸如行政、财务、人力资源、后勤保障等管理人员。这一忽视往往对审慎调查的效果影响重大，特别是依靠管理的企业更为突出。比如A企 业，我们在调查其人力资源部门时发现，该企业实际上存在着"一个人的公司"的问题，就是公司没有一个完整的管理团队，其发展主要依靠董事长或总经理的个人 品质和能力。虽然企业的管理制度表面看起来非常完善，管理架构健全，但董事长和管理层的责权不清，管理层的流动好像走马灯，3年之内换了5个销售副总和3个技术副总，大多数管理层成员在一起合作的时间不超过两年。这种企业的良好业绩多得益于所处行业的景气度，一旦竞争加剧，就会面临风险。

8点钟原则

投资者到企业考察时，有一个小的技巧非常有用，那就是选择与项目企业作息一致的时间到现场。比如企业8点钟上班，那你一定要在8点钟到企业，这就是"8点钟原则"。一家朝气蓬勃的企业，从上班那一刻起就可以判断它的活力。反之，对一家大面积存在员工和管理人员迟到的企业，在决定投资前一定要多打几个问号。
　　
在对企业的"8点钟"考察中，B企业有两点给我们的印象最深刻。它虽然有超过1 000名员工，但早上上班时全厂基本上没有一个人迟到。此外是厂门口的3幅标语："一怕苦，就要想办法，提高技术"、"二怕脏，就要讲卫生，爱护环境"、"三怕死，就要讲安全，避免事故"，朴实的道理让人对这家传统制造企业的管理充满敬意。

到过项目企业7个以上的部门

目前PE在 国内的投资对象以技术型企业居多，投资者在对企业现场进行走访时，当然要关注研发、市场、生产部门，但还应该详细走访企业的办公、仓库、物流、财务、人力 资源等部门，以对企业有全面、客观的了解和公正的判断。一家企业的成功是各个部门综合努力的结果，企业管理水平的高低也是企业各个职能部门管理水平的综合 体现。在对B企业的考察中，我们参加了一次生产经营会议，在与会人员中看到了财务、行政、保管和安全部门的负责人，各部门负责人的参与使得他们各个部门对生产经营计划的理解和执行渗透在日常工作之中，部门之间配合默契。

在项目企业连续待过6天
　　
投资者对项目企业的审慎调查虽然大多是"走马观花"，但也绝对不能蜻蜓点水，一带而过，连续在企业工作6个工作日十分必要。由此，投资者不仅可以看到企业日常的运作状态，还可以通过观察员工的加班情况来体会其文化、业务和生产情况。比如我们发现，虽然B企业和C企业的加班最多，但C企业的员工加班及薪酬制度不尽合理，员工满意度较低，而B企业则相反，满负荷紧张忙碌的生产使我们从另一角度看到了企业的市场能力。
　　
另一个案例也可以佐证6天调查的必要性。一次，当我们结束在企业的两天审慎调查之后，企业马上停止了生产，因为它的财务状况已经恶化到了付不起电费的地步，但这一点在其财务报表上却不见蛛丝马迹。

对团队、管理、技术、市场、财务5个要素进行详细调查
　　
影响企业最关键的有团队、管理、技术、市场、财务5个 要素，这也是投资机构需要着重关注和详细调查的。投资就是投人，团队的诚信、能力、凝聚力对企业的发展至关重要。对企业管理水平的考察则要集中在两个方 面，其一是管理制度的覆盖面、完善性，特别是内控制度的完善性；其二是管理制度的执行和效果。技术方面则要关注技术所有权的法律效力和技术的产业化程度以 及后续研发能力。对市场的调研主要看产品的市场地位、营销模式及现金流管理效果。对财务的核查除财务状况和结果外，更重要的是把重点放在财务的规范性和会 计核算的真实性上。这5个要素就像是企业发展的5根支柱，缺一不可。审慎调查要学会突出重点、找准关键的问题。从投资角度而言，在这5个要素上花时间和精力对决定投资是完全值得的。
　　
在我们对上述3家企业的调查中，最让人满意的管理团队是B企业，该企业核心管理团队拥有股份，而且管理水平也到位，它虽然属于传统制造行业，但由于市场开拓能力强，财务管理实行"实时全面预算管理"，存货周转天数不超过7天，产品毛利率比同行业高出3%。A企业虽然产品供不应求，但会计核算和财务管理不够规范，加之管理层变化大，产品质量不稳定。C企业的赢利能力指标最好看，管理水平也在改进之中，但企业负债率高，与员工的劳动合同也不完善。

至少访问4个上下游客户
　　
对项目企业的审慎调查还要包括其上下游客户，这种考察往往具有验证的性质。一般情况下，至少应该选择4个 样本企业，即至少有两个上游供应商和两个下游客户。对供应商的调查主要集中于与企业的供应关系，合同的真实性、数量、期限和结算方式；对下游客户的考察除 了对其与企业之间的销售合同相关资料进行核查外，还要看客户对企业产品的评价和营销方法。这不仅可以看到企业产品在市场上的竞争力，还可以通过调查发现企 业产品改进的空间。对投资者来说，在企业的产品竞争力上，没有什么比客户的评价更能说明问题了。

考察3个以上的项目企业竞争对手
　　
对竞争对手的考察有时比对项目企业的调查还要有用，因此，要选择与企业相关度最高的3个以上的竞争对手作为样本，比较竞争对手与项目企业的优劣，发现项目企业的竞争优势和不足，考量企业的市场地位和产品占有率。通过比较，我们发现，A企业的技术不错，但由于专业人才流失严重，有的甚至已经成为了竞争对手的技术负责人，与企业产品形成了潜在的竞争。B企业虽然目前不是行业领先企业，但其成长性大大高于行业平均水平，有在短时间内成长为行业龙头的潜力。C企业新开发的产品技术领先，但市场推广尚显不足。

要永远对项目企业保持20个关键问题
　　
作审慎调查的过程中，有一个技巧不能忽略，那就是去项目企业现场前一定要设计好访谈企业不同人员时的问题，要每次都对企业保持20个以上的不同问题。如何提问，如何设计，怎样找问题，这都需要在去企业之前先准备好。提问不仅是获得企业真实情况的重要手段，也是帮助企业提高管理水平的手段之一，更能反映出投资者水平的高低。
　　
要会问大问题，也要会问小问题，要学会问专业的问题，也要学会问轻松的问题。要将问题进行分门别类的设计，每次的问题都不相同。问题要越问越少、越问 越精、越问越细，从大到小地问。审慎调查的提问方法有两种，一是针对性的提问，第二是漫谈式的提问，要让企业家对自己的企业通过这些问题思考一遍，即使对 其了如指掌的问题也要再思考一下。这些问题也能让企业家了解投资机构在关心什么、思考什么，以便于双方在投资后的协调与配合。

至少与企业普通员工吃一次饭
　　
与普通员工谈企业是作审慎调查的一种有效渠道，投资者一定要找机会与员工至少吃一次饭，利用这种非正式的机会和员工交流。对于依靠人力资源和管理的企 业，这是一定要走的步骤。从员工的谈话中得到的信息，有时比企业管理者按照商业计划书准备的问题所带来的信息更能反映企业的问题。正是在与员工的交流中， 我们发现A、B企业的员工对企业的满意度都高于C企业。因为员工对企业的信心和态度往往反映了企业的核心竞争力，类似于C的企业，不管其技术、市场有多好，投资者未来都会面临风险。因此我们提出，让C企业重新和员工依据《劳动合同法》签订劳动合同，为员工购买社保，改善其工作条件，留住核心岗位员工，以保障员工的稳定性。
　　
突出重点、关注细节、重视程序是审慎调查成败的关键。经过以上9种方法的审慎调查，投资者对于企业的情况一般都可以形成比较全面的认识，并可以对是否投资作出初步的决定。从ABC三家企业的案例看，B企业管理规范、成长性好；C企业虽然与员工的劳动关系不完善，但企业管理层愿意改进，且企业赢利能力强，通过改善管理、扩展市场渠道还可以进一步提升赢利水平，这两家企业最终都进入了投资委员会的会议，受到投资者的青睐。A企业虽然技术领先，但管理层变换频繁，是投资的硬伤，不符合我们的投资理念。
 
除了投资，还投什么？
　　
可能到来的冬天对本土PE提出了更高的要求，其商业模式需要从原来"投资+上市服务"的1.0版本向"投资+管理服务+专业整合+资本运作"的2.0版本提升，那些依赖Pre-IPO项目投资、缺乏提供管理服务能力的PE将受到考验。
　　
"做我们这一行的只有两种结果，要么赚回一堆钞票，要么抱回一堆电脑，没有中间道路。"一位资深投资专家给我的忠告，揭示了PE投资的极端性，VC的投资更是如此。PE的投资是以退出为导向的，如果项目企业的价值不能增加，就意味着投资失败。2008年6月以后，随着美国次贷危机的多米诺骨牌效应进一步显现，世界金融危机在全球不断蔓延，本土PE迅速遭遇流动性退潮的冲击，以前"投资+上市服务"的模式开始受到挑战，越来越多的投资项目IPO被推迟，已经上市的项目股价持续下跌，多数项目企业当年的经营目标看来难以完成。过冬论弥漫之下，考验PE水平的时候到了。PE除了投资，还需要为企业做什么--这个简单而又重要的问题，在目前PE热潮退却时，再次开始引起了市场人士的思考。

投资＋上市服务：Pre－IPO模式的原罪
　　
与国际著名的PE投资机构相比，本土PE除了资金规模、专业投资能力和经验方面的不足之外，还有一根软肋是投资后的增值服务和项目管理。本土PE要么是广种薄收，只投资不管理；要么一投资就派人紧盯着资金，怕项目企业乱花钱。更重要的是，其对投资项目的增值服务相比国际知名PE差距较大，往往限于投资与上市服务两个环节。
　　
由于投资向后是本土PE的主要特点之一，加之中国的并购市场还很不发达，上市是PE最为看重的退出方式，因此，Pre-IPO项目成了PE追逐的目标。这种项目企业的管理、技术、市场、财务都相对成熟，企业的规范性由投资银行、会计师、律师按照资本市场的要求把关，PE所能提供的服务就只剩下帮助企业打通上市通道，介绍投资银行、会计师和律师，提供包括吃饭喝酒在内的相关事宜了。
　　
只要能上市，在国内资本市场供需还不平衡的情况下，PE的投资一般都能有所斩获。由于本土资本市场的结构性问题，法人股全流通也不过是这两年的事情，资本市场的形势好坏成了PE发展的风向标：资本市场好，PE就热；市场一熊，PE就降温。本土PE的两轮热潮与国内资本市场的上涨在时间上完全吻合，PE完全成了资本市场的俘虏，IPO成为很多本土PE的指挥棒，以至于出现了多家投资机构在一些Pre-IPO项目上大打价格战的情况，这类故事成了2007年本土PE圈中最热闹的话题。越不需要资金的企业，PE越是追着投资；而对于早期的项目，除了拥有专业能力的PE外，少有投资机构问津。PE成了只投资不服务、坐等项目企业上市后卖股票的阔太太，这是本土PE受到责难的原因之一。
　　
这种以Pre-IPO为主的项目投资，成本相对较高，在资本市场出现调整、国家宏观调控的情况下，一旦IPO推迟或失败，PE的退出变现就变得不可预测，投资的风险就会显现。

投资＋管理服务：专业PE的功力
　　
到美国的PE和VC机构参观，你会发现和本土投资机构不一样的现象：钱多，人少，年龄大。第一，基金的规模都很大，超过10亿美元的基金比比皆是；第二，作为基金管理者的GP不多，但每人都是投资专家；第三，GP的年龄都很大，五六十岁很普遍，70多岁也不足为奇。这是美国PE行业多年来专业化发展的结果。
　　
专业的机构需要专业的人来管理。一方面，美国的养老金、保险资金和大学基金等长线资金进入PE行业后，需要寻找有经验的专业人士来管理；另一方面，美国许多GP都是行业和企业管理专家，他们做投资之前都在企业工作多年，具备丰富的创业、管理和上市等成功经验，特别是其多年积淀的行业经验和资源对于PE来讲是最宝贵的财富。这些成功人士做GP，除了投资并为创业企业提供上市辅导方面的增值服务外，还可以凭借经验为企业提供管理、战略等方面的深层增值服务。
　　
PE是个重积累的行业，专家型GP是实战中练出来的，投资多了，经验就丰富了。这种经验是建立在对不同类型企业评估、选择、管理的数量积累上的。一个称职的GP，实际投资的企业占其所收到商业计划书的比例一般不会超过5%，占审慎调查过的企业比例不会超过50%。这种建立在大量经验、教训上的投资，往往会把GP锻炼成集投资、资本运作、行业整合和企业管理经验于一身的专家，令他们可以有效改善项目企业的管理，提升自己投资的价值。
　　
专业的PE是创业企业的教练，对于创业者来讲，PE带来的企业管理经验和专业知识，可能比资金更为重要。在很多成功企业的背后，都有知名PE或VC对其管理和资源整合的推动，如雅虎和谷歌的成功不乏红杉资本的助力，透过百度可以看到 IDG的影子，从无锡尚德的成功也可以看到高盛集团和3i集团的作用。
　　
在中国，许多创业团队都会告诉PE："除了钱，其他什么都不缺。"而在专业的PE看来，除了钱以外，创业企业普遍存在的问题是：一缺规范，二缺人才，三缺战略。PE界有句经典的话："能用钱解决的问题，都不是问题。"其实，最令投资人头痛的是创业企业在管理，特别是财务、税务管理上的不规范，许多业绩很好、行业前景非常不错的创业企业，可能就因为一个创业者这样或那样的"硬伤"而被PE放弃。即使是被投资人青睐而投资成功的项目，PE下工夫最多的也是如何让创业企业走上规范之路。从现阶段看，本土PE在促进项目企业的规范化运作上有两点最值得称道：一教开会，从股东会、董事会开始，让企业按《公司法》的要求规范管理，减少家族色彩和管理的随意性；二教缴税，让企业遵循国家的有关法律规范，按章纳税。仅就这两点来讲，本土PE就功不可没，这应该也是国家鼓励和大力发展本土PE的原因所在。
　　
不过相比之下，本土PE在改进项目企业的人才、管理、战略、市场拓展、资本运作等方面所提供的帮助还是比较少。为企业提供深层增值服务的能力以及对早期项目的判断能力，是本土GP与外资GP的一大差距所在。本土GP对行业和企业管理的经验积累都还不足，需要学习和提高，只有既会投资又能帮助企业改善管理、制定战略、提升业绩，PE才能保障投资项目的成长，从而炼成金刚不坏之身。否则，就应了那句话："投资前它天天想你，投资后你天天想它；投资前意气风发，投资后担惊受怕。"除了烧香祷告、坐等IPO，什么也做不了，投资就会变成轮盘赌。
　　
实际上，PE投资是与所选择的创业团队在其一次创业基础上的二次创业，是以资金和利益的捆绑为纽带，PE通过投资把自己和创业者放在一条船上，双方共同努力、共同发展。因此，对PE来说，没有管理服务的金刚钻，光做有钱投资的瓷器活，恐怕揽得下活却出不了活；对创业企业来说，在融资时也需要借一双慧眼，"穷得只剩钱"的PE，不会给企业带来实质性的价值。

商业模式变革：PE过冬的本钱
　　
2008年下半年泛滥的流动性潮水正在退去，不管你愿不愿意，PE的冬天真的来了！原来GP打着"飞的"满世界投资的景象正在改变，静下心来的PE正考虑着怎样度过已经临近的冬天。环境变了，创业的难度正在加大，以前的市场格局发生了变化，年初还受到"抢购"的产品，一转眼就变成了"滞销品"。在这种形势下，与其所投资的中国企业一样，本土PE目前也面临着商业模式的升级，其投资管理模式需要从原来"投资+上市服务"的1.0版本向"投资+管理服务+专业整合+资本运作"的2.0版本提升。PE的投资只有内含帮助企业提升内在价值的服务，才会真正"值钱"。市场上也不乏这样的案例。
　　
在2002年的上一轮VC低潮中，一家本土著名PE在投资一个项目后，首先改变了项目企业的销售模式，将其全国13家子公司重组成按区域划分的6家不具法人地位的分公司，从而减少了营销费用，避免了以前出现过的管理失控的风险；在投资条款上，要求项目企业对核心管理层实施10%的期股期权激励计划，并提出了具体的实施方案，让包括总经理和技术总监在内的11名骨干持有了股份，大幅提高了管理层和核心员工的积极性。同时，这家PE还利用自己海外投资方的优势，为项目企业开辟了海外市场渠道，使项目企业的出口订单比投资前增加3倍多，公司的业绩比投资前年均增长30%以上，销售收入从投资前的8 000多万元增长到近10亿元，利润从投资前的400多万元增加到1.1亿元。目前，这家项目企业已进入上市前的最后准备阶段，与最后一轮投资者的估值相比，2002年进入的这家PE投资已增值5倍多，相信资本市场会为其带来可观的现金收入。由此可见，PE较早介入、通过全方位增值服务培育企业得到的回报，要比Pre-IPO模式的投资回报高得多。
　　
从20世纪90年代末期开始，本土PE经历了十几年的实战考验，虽然中间经过两轮热潮，但真正创造的成功案例并不多见，与外资PE在中国的战绩比起来，本土PE的水平似乎还停留在改革开放初期的20世纪80年代。前途光明，问题不少，市场冷了，PE也应该冷静，但信心不能冷。业内已经提出了"深挖洞、广积粮、缓上市"的过冬口号，PE应当利用市场调整的机会，苦练内功，提升投资管理和增值服务水平，真正做企业的教练和帮手，"投资一块钱，还要投资一块钱的服务"，才是PE的价值所在。现在的市场风险和机会相伴，机会是跌出来的，PE的成功之道就在于：在市盈率低的时候投资，在市盈率高的时候退出。只有具备全面服务能力的PE，才能在退潮时依旧畅然潜泳，抱回一堆现金而非一堆电脑。

#+END_VERSE

#+BEGIN_HTML

<!--#include file="footer.htm" -->

<!--http://changyan.sohu.com/-->
<div id="SOHUCS"></div>
<script>
  (function(){
    var appid = 'cyqS3WUfe',
    conf = 'prod_ec99dd0bbd9458bc47d4b550b55aa1b2';
    var doc = document,
    s = doc.createElement('script'),
    h = doc.getElementsByTagName('head')[0] || doc.head || doc.documentElement;
    s.type = 'text/javascript';
    s.charset = 'utf-8';
    s.src =  'http://assets.changyan.sohu.com/upload/changyan.js?conf='+ conf +'&appid=' + appid;
    h.insertBefore(s,h.firstChild);
    window.SCS_NO_IFRAME = true;
  })()
</script>  

#+END_HTML
