#+INFOJS_OPT: view:info toc:nil   mouse:underline buttons:1 path:./inc/org-info.js
#+STYLE: <link rel="stylesheet" type="text/css" href="./inc/css.css" /> 
#+STYLE: <link rel="icon" href="http://orgmode.org//org-mode-unicorn.ico" type="image/ico" />
#+OPTIONS: H:4  num:nil  toc:t  \n:nil @:t ::t |:t ^:t -:t f:t *:t TeX:t LaTeX:t skip:nil d:(HIDE) tags:not-in-toc creator:nil 
#+TAGS: Modeling(m) Tutorials(t) Benchmarking(b) Hack(h) FAQ(q) Money(y)
#+AUTHOR:G$D
#+TITLE:Reading
* 郑永年 -  社会变革
** 郑永年: 中国机构改革为什么要向社会分权？
郑永年专栏

　　中国的大部制改革为什么必须向社会分权？道理似乎很明显。向社会分权是大部制改革成功的前提条件。向社会分权有三个基本目标。其一是真正促成政府从无限政府向有限政府的转型；其二是赋权社会；其三是构造政府能够监管社会的制度结构。

　　向社会分权是关键。很简单，如果政府不能把权力下放给社会，什么权力还是自己掌握，还是什么事情都管，那么就很难实现“大部制”的目标，很难实现有限政府。但政府向社会分权并不是一件简单的事情。这里有几个重大问题需要厘清：政府应当做什么、不应当做什么？什么权应当留在政府、什么权应当下放给社会？社会应当作什么、不应当做什么？

　　从各国经验看，有一些事情必须由政府来做，例如外交、法律、司法、国家安全、社会稳定、暴力垄断等等。在这些领域，政府必须花大力气来做，不管有什么样的代价也必须做好。例如，既不能让社会来管理监狱，更不能让社会来设立和经营类似监狱的组织，否则就会出现前些年那样的“黑监狱”的情况。再如，警察的权力不能下放给社会，否则就会导致暴力的滥用。警察领域专业性非常强，不可随便下放给社会。但在其他很多领域，尤其是社会、经济、文化等诸领域的权力可以下放给社会，社会在这些领域可以扮演很大的角色，甚至是主角。尽管这些领域政府也可以自己来做，但还是下放给社会更有效。

　　广东等省的一些地方在实行“大部制”之后，也产生了只有“物理反应”而没有“化学反应”的情况。就是说，在把很多政府功能部门整合起来之后，没有及时地把权力下放给社会，于是就出现了一个局存在很多副局长的情况。如何从“物理反应”进展到“化学反应”？就是要把大量的行政权力（主要是行政审批权）下放给社会。这个目标，广东已经相当明确。当然，这是一个过程，不是一天、两天就能完成的。从这个角度来说，如果出现很多个副局长的现象是转型性的，就是为了减少改革阻力的一种阶段性安排，那么也无可非议。但必须强调的是，政府权力必须下放到社会，否则就不可能实现真正的大部制改革。如果不把很多权力下放给社会，这种做法只是机构的整合，并且是毫无意义的整合。

下放权力实现小政府和有效政府

　　也很显然，这种情况在中央层面也存在着。“大部制”改革首先在中央层面展开，然后再扩展到地方层面的。在中央层面，这一改革的第一步也是机构的整合。但机构整合之后，并没有真正放掉权力，政府的功能也没有减少。这尤其表现在发展和改革委员会的变化方面。顾名思义，发改委本来就是要做宏观发展和改革方案的。但是，现在这个机构已经演变成为无论是宏观还是微观都管理的庞大机构。其它部委机构也差不多，每次改革会取消一些部门，但每次改革之后，各种部门又会以各种方式重新出现。中央29个部委就有2000多个挂靠机构（根据前国家审计署审计长李金华的统计）。这是没有向社会分权的必然结果。直到前不久，国务院才根据广东等地方的经验，开始出台相关下放行政审批权的文件。

　　不向社会下放权力，就实现不了小政府和有效政府。但同样重要的是，必须指出，向社会分权的过程中，不能把社会过于理想化。很多人因为对政府行为不满，往往把社会过度理想化，相信一旦分权给社会，什么问题都解决了。这样的想法也不符合实际。实际上，“小政府、大社会”的概念在改革开放早期的1980年代就已经提出来了。当时有关方面想在海南省进行试验，但并没有结果。主要的原因并不是这个思路问题，而是因为当时社会力量还不发育。市场、社会，这些概念并非抽象，是长期历史发展的产物。也就是说，它们的产生、发展到成熟需要很长时间。

　　到今天，改革开放已经30多年了，中国社会发生了巨大的变迁。但即便如此，在很多地方，社会还是不发达，政府还是在操控一切。沿海地区经济发达，其社会力量远比其他地区发达。但即使在沿海地区，社会力量成长快，并不能简单地说社会就已经具备了能力来自我管理，或者有能力接受政府下放来的权力。

　　鉴于社会不够发育这种现状，广东等一些地方的现实主义方法就是设置“法定机构”。法定机构（statutory board）介于政府和社会之间，是一种半政府和半社会的机构，新加坡、香港等地相当流行。因为社会力量还没有发达起来，还没有能力来承担政府下放的权力，政府就首先把权力交给法定机构，由法定机构代表政府来行使权力。法定机构可以是永久性的，也可以是转型性的。在社会发育成长之后，法定机构就可以完全社会化，或者把权力移交给其他社会力量和组织。但也可以是永久性的，在一些领域，权力的行使需要政府的参与，法定机构就是政府和社会合作的平台。但可以预见，在今后相当长的一段历史时期里，现实地说，法定机构不失为政府分权于社会的最有效有序的方法。


中国现在正在进行的事业单位的改革，实际上也可以在法定机构这个概念构架内进行。事业单位就类似于法定机构，只不过是较之法定机构，事业单位更靠向政府。中国的事业单位设置基本上参照公务员系统，是政府的延长。事业单位实际上可以通过改革转型成为法定机构。尽管政府仍然可以向法定机构拨款，但法定机构则可以独立操作，引入市场机制，从而提高运作效率。从香港和新加坡的经验看，设立法定结构是政府向社会提供服务的有效方法。

　　也应当意识到，政府向社会分权并不意味着政府和社会完全不相关了。恰恰相反，政府一方面从直接控制和管理社会退出，另一方面也必须对社会力量和社会组织进行规制，实行法治。不能天真地假定社会就是好的。人们需要的是一个好社会，而不是坏社会。恐怖主义、邪教、黑帮等等都不是人们想见到的社会力量。如同政府会犯错，社会也同样会犯错。因此，正如在经济领域政府要规制市场一样，在社会领域政府也要规制社会力量和组织。就是说，政府在实行向社会分权的同时，必须建立起一整套规制社会的制度。规制社会是“大部制”改革的有机部分。

分权和立法监督社会过程并行

　　现在一些地方开始实验向社会分权，但是如何通过立法来规范社会和监管社会，还没有提到议事日程上来。这种情况必须改变。人们可以从早期经济领域的分权学到很多经验教训。中国的经济分权主要方式有三种。第一种是改革开放之后在国有企业之外发展出来的民营企业。第二种是上世纪90年代中期之后“放小”的产物，也就是原先中小型国有企业通过“民营化”演变成为民营企业的部门。第三种就是国有企业内部的分权，就是权力从中央下放到地方政府。但是在所有这些领域，权力分到企业了或者地方政府了，但中央政府对企业的监管没有到位。结果造成了大量的企业经济行为，和社会整体利益背道而驰的情况，例如大量的毒食品、违规生产、不安全等等。当然，这些现象的产生也并不符合企业本身的利益。如果分权和法治基础之上的监管同时进行，这些情况可以得到控制，甚至避免。等到企业在没有监管的情况发展成长起来之后，政府再要去实行监管，就会面临巨大的困难。现在面临的就是这样一种局面。

　　社会领域也会是一样的逻辑。如果当社会力量成长起来之后，再去立法规范和监督它们的活动，那会是一件非常困难的事情。各国的经验都是如此。中国本身也有这样的情况。例如互联网的实名制制度。如果一开始就要求实名，什么困难也没有。但现在等到互联网已经壮大，再要去实行实名制，不仅很困难，成本也极高。今天的情形就是这样。不仅企业（互联网公司）反对这样做，顾客（社会成员）也反对这样做。前者是为了商业利益，而后者则倾向于把实名制视为是政治控制。

　　所以，向社会分权的过程和通过立法监督社会的过程应当同时进行，是同一个过程。尽管中国有关方面已经宣布，社会主义法律体系基本建成，但实际上社会立法基本上还是一个空白。改革开放以来，大量的立法是经济立法，是为了推动经济发展的。这种局面有其历史性，因为早期的主要任务是为了发展经济，没有条件把社会改革提到议事日程上来。但到现在这个阶段，当社会改革变成改革主题的时候，必须把重点转移到社会立法上来。政府和社会团体之间的关系、社会团体之间的关系、政府与宗教组织的关系、宗教组织和其他社会组织的关系、新型非政府组织和传统社会组织（例如共青团、妇联、工会）等等，都需要通过立法来规范。

　　从2003年到2013年，大部制改革从中央开始到地方已经有10年了，但除了一些机构的整合之外，并没有取得很大的进展。这主要是由于改革者所强调的是行政体制的内部改革，即权力在官僚机构之间的重新调整，而没有考虑到从行政体制到社会的分权。如果不能向社会分权，大部制改革不会有很大的前途。向社会分权，则行政体制改革已经超出了自己本身的范畴，而进入政治改革领域。这也就是为什么说行政体制改革到了今天的阶段，需要政治改革的推动，否则改革者难以进行任何有意义的机构改革。

作者是新加坡国立大学东亚所所长

文章仅代表个人观点

如果当社会力量成长起来之后，再去立法规范和监督它们的活动，那会是一件非
常困难的事情。

http://www.zaobao.com/yl/yl130226_001_1.shtml
* 咨询行业信息
** 麦肯锡为什么不上市？
#+BEGIN_VERSE
麦肯锡为什么不上市之一――刘行歌的解释 
 首先，我们应该考察上市的目的，一般有三个： 
1、fund 
2、image 
3、market expansion 
然后，我们看麦肯锡是否有这样的需求 
1、2麦肯锡都不缺，这样的公司一般是不缺cash的，而它的image已经足够好了，在nyse 
挂个名对它几乎没有什么收益，例证，与远大空调也没有上市，因为它不缺钱，虽然它是 
制造型企业。 
3是咨询公司发展中的一个重要特点 
总的来说咨询公司都希望扩大自己的市场份额，但扩大份额是有前提的： 
1、demand 
2、outstanding product 
1需求应该是存在的，企业越来越的从咨询公司获得帮助，但2带来了新的疑问 
咨询公司是否可以通过融资来迅速扩大自己的产品线？ 
1、咨询公司提供的产品――解决方案是非同质化、非标准化商品。 
既它的产生是基于优秀的，受过良好的训练和经验的积累的人创造的，所以，麦肯锡公司 
的市场扩张是基于他们的生产线――员工的扩张，而不像制造型企业，可以通过增加生产 
线短期内迅速扩张。 
这样的公司特别注重知识的共享和知识的转移，尤其是麦肯锡习惯采用“面对面讲，手把 
手教”，他们认为有些知识通过文档是不可能真正理解和吸收的。因而，他们的员工不可 
能在短期内，大量的产生，所以通过融资对麦肯锡而言，并不能达到市场扩张的目的。 
2、由于解决方案是不能量化的。 
即不是通过最后咨询报告页码的多少决定的。甚至，客户可能不用咨询公司的方案。所以 
，咨询公司的收费方式不是project fee,而是hour fee。这更加说明他们的收益来自于员 
工的扩充。例证，律师事务所主要也采用hour fee,因为他们提供的服务的性质与咨询公 
司相似，律师不能以案子的胜负来收益――风险太大。但个别小case也有project fee。 
综上所述，上市对麦肯锡这样的顶级战略咨询公司几乎没有收益 

其次，我们看上市公司的成本 
1、entry cost 
2、operational cost 
1大概也就几个million,基本上可以承受 
2可以细分为 
（1）将公司基本信息透露给大众和竞争对手，如盈利率、现金流 
（2）长期与政府、股东进行交涉，平衡大家的收益、支付高昂的法律费用，如股东权益 
问题 
这样的成本不是每一个公司愿意承受的，尤其当它的上市受益不大的时候。例证，美国纽 
约一家公司（具体名字忘了）由于不愿意支持（2）――长期打官司，第一股东在nyse将 
其他股票悉数购进，最后撤市。 

再次，对于KPMG的上市，我的理解是它发展的业务主要是IT CONSULTING。其中的知识更 
加结构化，更加容易复制。但据说效果不好。 

但，还有一些疑问 
如为什么高盛作为投行是上市公司？而且他们是PROJECT FEE。 

这个问题不能算是个学术问题，但有助于我们进一步理解咨询公司的特点，期待大家进一 
步讨论：） 

http://bbs.vsharing.com/Management/Consulting/257280-1.html

#+END_VERSE
** 毕博破产：到底谁给咨询公司做咨询
毕博破产：为了忘却的纪念--到底谁给咨询公司做咨询 

 继世界500强的北电网络申请破产保护之后，2008年2月19日, 世界最大的咨询公司之一的毕博申请破产保护。作为长期关注咨询行业发展的第三方研究者，毕博一直是我非常尊敬的同行前辈，当年的黄辉带领毕博创造的辉煌业绩，以及黯然离开之后主政均瑶，都让人怀念毕博昔日的不凡表现；当年的学习榜样今天竟然会以这样一种方式谢幕，不免让人深感凄凉。 
 难道真的是应了那句话，做医生的，救的了别人，却治不了自己么？ 

 2005年4月，毕博的管理及IT咨询部门需要2亿美元滚债，以此偿还即将到期的其他信用凭证。毕博还债，主要是因为从2004年开始，毕博在纯收益为负的情况下仍大量举债，以达到快速扩张的目标。其负债水平快速提高，特别是长期负债，从原先的4亿美元增至最高时的10亿美元。2005年，毕博借钱还债，举手之劳，多家金融机构组成的贷款联盟很快就将这笔钱打入毕博的户头。在它们看来，这间拥有大量政府订单、股价过百的公司绝对是优质客户，更何况这笔借贷还被赋予了债转股的选择权，让债权人拥有充分的想象空间。 
好景不长，金融危机爆发后，毕博的股价急速下挫。从2008年1月份的每股100多美元暴跌至今年年初的不到2美元。就在这个时候，那2亿美元的可转债即将到期。此时，精明的债权人肯定不会再做债转股的傻事，用那么一大笔钱去换一堆已为废纸的股票，因此，毕博只有按期还款一条路可走。就这样，凑不到足够现金的毕博选择了破产保护，期望以此寻求债务重组的机会。 

　　按照毕博向法庭提供的破产计划，该公司希望取消所有现有的外部流通股，并向偿还等级较低的无担保贷款方提供普通股。同时，一笔5亿美元的信用贷款将被转换，取而代之的是2.72亿美元附加利息的长期贷款以及价值1.3亿美元的综合信用贷款和优先股。如此，可以在一定程度上减轻毕博的债务负担，也为其实现债务展期，腾挪资金打开了方便之门。 
　虽然在毕博看来，这是最佳的解决方案，但能否获得通过，尚未可知。这将取决于最终文件中是否有充分的数据支持，相关细节是否符合破产法条例。为此，毕博雇佣了三家专业公司提供相关的财务和法律服务。倘若这最后一招也不灵验，毕博将不得不面对被分拆出售的命运。; v" K2 J8 i% b! p( H7 @ 

现在看来，麦肯锡的不上市的确是深谋远虑，除了公开解释的原因以外，还有一种以防万一的远见卓识，估计现在麦肯锡的大佬们肯定更为自己的聪明决策感觉到鼓掌欢呼。 

也许有人说：咨询公司都申请破产了，那以后谁还敢用咨询公司呀？我想说的是：其实问题没有您说的这么简单。这要从咨询公司的出身开始说起： 

伟大的思想家恩格斯曾经说过：“历史是至关重要的，人们过去的选择决定了现在及未来可能的选择”。世界上第一家管理咨询公司，那应该是1886年由麻省理工学院教授阿瑟 利特尔（Arthur Dehon Little）创立的ArthurD．Little（通常简写为ADL）公司，不过它当时的咨询领域主要是在工程和技术领域。而1914年成立的博思艾伦（Booz Allen Hamilton）公司则声称自己在全球第一个提出了“管理咨询（Management Consulting）”的概念。但既然是“管理咨询”，而且我们也认可真正的管理理论是源于“科学管理之父”泰罗的话，那似乎应该把他从事管理顾问的那一天算做是管理咨询真正的诞生日，或者至少是把他称为世界上第一个管理顾问。 

在战略咨询领域，众多我们耳熟能详的名字：麦肯锡，科尔尼（A.T.Kearney），波士顿（BCG），贝恩公司，罗兰贝格（RolandBerg），摩立特（MonitorGroup），博思艾伦。在管理咨询业的发展中，还一直有着这样两股力量，他们与高端的战略咨询时而分开、时而交融，共同构成了管理咨询业的发展洪流，一类是人力资源咨询公司，比如韬睿咨询公司（Towers Perrin），翰威特咨询有限公司（Hewitt），合益（Hay）集团，华信惠悦咨询公司（WatsonWyatt），美世人力资源公司（Mercer Human）。与管理咨询结伴而行的还有技术的力量。为此，我们又将提到会计这个行业。咨询行业的发展与会计行业确实有着非常密切的关系，麦肯锡是一个会计学教授，而泰罗也是在掌握了一套会计方法后才开始尝试从事顾问工作。从某种意义上可以说，是会计业在引领着咨询业的发展，比如普华永道，安永和毕马威。随着信息化的推进，企业IT咨询也在上个世纪90年代成为新的热点，IT咨询的特点在于其咨询过程更多地与计算机和流程结合在一起，强调通过IT项目的实施来帮助咨询方案的真正落地和产生效益。他们强调的是“整合”，整合战略、人力资源、业务和管理流程，更重要的是，整合进IT的工具和思想，整合进IT的软件和硬件。以毕博为例，他们认为公司之所以不同于其他特殊功能领域（战略或人力资源）的管理咨询公司，就在于其提供的是包含企业战略、业务流程、信息技术和人力资源的完整的解决方案。 

管理咨询行业在上个世纪上演的一幕幕对麦肯锡的“挑战史”。在这样的挑战中，全球管理咨询行业不断发展，并最终产生了上述的世界管理咨询巨头。事实上，在写作本章的时候，笔者一直怀着一种对这些国际咨询公司深深的敬意。 

但是，管理咨询行业已经很完美了吗？显然不是。不仅仅是因为毕博申请破产了，也不是因为曾经的德隆也曾经是这些国际著名咨询公司的最佳客户，德隆在鼎盛时期，几乎邀请过所有在中国开展业务的知名跨国咨询公司进行过咨询项目的合作，但花大价钱任用过众多洋智囊的德隆，最终未能避免坍塌的命运。 

咨询公司在整个商业价值链上，是不是应该成为一个死循环？死循环的意思就是他作为一个商业价值提供者，只需要输出，不需要输入？或者单纯靠自己的修饰和调整就足以保证自己的安全和壮大？答案显然是否定的。 

那一个很深刻的问题就出来了：到底谁可以给咨询公司做咨询？ 

在不久之前，曾经有机会与从大洋彼岸的两位MIT斯隆商学院的MBA学生交流，他们专程来中国大陆做关于咨询公司合伙人管理制度调查的课题研究，也涉及到咨询公司的组织结构创新和薪酬激励制度等。在笔者看来，咨询行业作为一个新兴行业，尽管每天在给众多实体经济做着顾问和咨询，其实自己行业的管理积累是相当初级的，至今为止还没有出现一个行业是专为咨询行业提供公司治理解决方案的。这好像不能用一句医者不自医来简单搪塞如此复杂的行业问题。 

我们知道，咨询公司的巨头做生意的一个重要途径是强大的“校友”网络。在很多国际咨询公司的网站上都看到一个栏目“alumni”（校友录），专门介绍离开公司后去其他企业服务的杰出人士。而这些“校友”领导下的公司也自然成为他们最为稳定的客户来源。还有就是咨询巨头都有着强大的知识管理体系，每个国际咨询公司都已经建立了一套庞大的知识库，在里面你可以了解到公司的方法论、公司的咨询工具、公司的案例、公司对各个领域不同的观点。公司的员工可以搜索到这家咨询公司在全球各个行业领域、各个功能领域的所有案例和知识。这个“知识中心”是不断更新的，这就是一种底蕴，是他们最大的竞争力所在。这是以往众多咨询巨头赖以生存的法宝。 

新世纪里，咨询行业从2001年开始正是遭遇了这样一场“创造性破坏”。这场破坏是从安然事件开始的。这场破坏带来的损失无疑是巨大的，普华永道对此应深有感触。该公司在2000年初曾表示年底前将其管理咨询业务分家，当年9月惠普就表示希望以160亿至180亿美元股票与现金购并其管理咨询部。但公司领导层一直希望将其咨询业务公开上市，甚至给新公司取好了一个叫做“星期一”（Monday）的奇怪名字。可惜，由于世道从2001年开始突然低迷，上市未能成功，加上面临着分拆的巨大压力，不得不被迫以35亿美金的“跳楼价”在2002年7月转让给IBM。要知道，普华永道咨询在2001年的营业收入仍然高达50亿美元；而安永在2000年将其40亿美元的管理咨询业务卖给凯捷时，可是整整卖了124亿美元。 
安然事件给过去那些传统的咨询巨头们都敲了当头一棒，同时也给新兴的咨询公司们打了一针强心剂。伴随着咨询行业从2001年开始的暂时低迷，大家开始反思咨询巨头过去那些所谓“成功”的业务模式，开始反思咨询行业那些以前被视为是“真理”的金科玉律。在这样的反思中，人们看到了希望，“打败麦肯锡”在新的世纪里似乎才真正成为了可能――因为人们看到了一场真正的“创造性破坏”。 
任何行业都逃不过创新的宿命，昔日的巨头，可能明天就会死去，毕博的破产让我们坚定这一点。人们发现，客户的需求在新的世纪里发生了根本性的变化。他们希望的是更精干的咨询团队、更短的咨询周期、更低的咨询价格，希望项目的费用和进程更易于跟踪，而项目的价值更容易“计算”并获得更大的投资回报。其中的关键是，客户仍然需要咨询，但他们希望聘请的是更多有经验的真正的专家来帮助企业解决实际问题。这样一来，传统咨询公司的管理模式会存在根本性的不适应。 

　　咨询巨头们通用的是一种“金字塔”式的管理模式，位于塔顶的是数量很少的合伙人，位于中间的是一批经理和项目经理，而处于塔基的是数量庞大的由MBA组成的咨询师以及由大学刚毕业的学生担任的分析员。在这种模式下，“当你聘请麦肯锡时，他们会先来一名高级董事、一名高级主管、一名初级主管、一名高级合约经理、一名合约经理以及一名项目经理。此时，你还未见到替你真正干活的人。这是一种相对来说高价位、缺乏弹性的模式。” 

　　这种模式也正是那些国际咨询巨头们赖以成功的最根本的业务模式。通过这种模式，由于在报价的时候会考虑那些合伙人、经理的高额工资，所以公司将可以获得更高的收入；另一方面，这些合伙人、经理的名字又可以同时出现在很多项目中，这又使得他们能同时运行很多项目、获得更多的收入。这种模式也是与他们“要么提升，要么走人”的企业文化相适应的：公司从大批的分析员、咨询顾问中提拔出少部分的精英出任经理乃至更少的“精英中的精英”出任合伙人，同时不断地吐故纳新，招入大批刚毕业的要价更低的MBA。这些人是真正在客户那里一呆就是几个月的人，是真正跟客户打交道或者说真正干活的人，而他们同时又是“相对廉价”的劳动力，这又可以使公司可以获得更高的利润。这正是国际咨询巨头们迅速扩张的最大秘密，是他们过去成功的基础。 
可是这种模式正是现在的客户最不想要的模式，正如美国管理咨询公司协会（AMCF）主席彼得?布朗所说：“客户不会再像原来那样容忍很多年轻咨询师在公司里跑来跑去”。他们需要由训练有素人员组成的小型、灵活的团队，这些人应该拥有多年的专业知识和经验。现在看来，也正是咨询公司的这种公司结构使得咨询巨头们陷入恶性漩涡不能自拔，以前貌似先进而灵活的合伙人制度现在却会把公司带入不归路，这其中还没有考虑合伙人离开的风险在内。国内众多咨询公司的老总们努力学习咨询前辈的先进经验，却没有想过，我们学到的同行的所谓成功经验可能已经面临被市场淘汰的危险。 

也许最先死掉的就是这些我们曾经顶礼膜拜的前辈，而作为后来者的中国背景的咨询公司，却可以趁着国内客户依然并不是很成熟来赚的一杯羹，当然总有一天，国内的咨询行业巨头也会步毕博公司的后尘，只不过这个时间可以稍微延缓几年，这应该是国内几家著名咨询公司的领导人应该思考的战略性问题，也许他们来不及想这些问题，也许已经有了解决方案。 

更重要的是，在这个“创造性破坏”的巨变时代里，咨询业面临的决不仅仅是这样一场从“金字塔到钻石”的组织结构变革。笔者认为，我们对咨询业过去的很多成功做法都有必要进行一次系统的反思，这里包括做咨询的方式、包括给客户的产品、甚至包括对“咨询”的定义。因为在这个时代里，唯一不变的只是“变化”而已。而对中国的咨询公司来说，更加应该去进行这样一场反思：因为我们本来就没有所谓“成功经验”、“传统做法”的束缚，所以更加有责任去打破崇拜、大胆怀疑；同时我们更加应该有动力去进行这样的反思，因为我们本来就几乎是一无所有，而如果在其中寻找到成长的机会，那可能就会赢得整个世界。 

一句话：咨询行业不能简单学习外国，也需要深度创新，否则总有一天会走这些行业巨头的老路。 

来源: http://hi.baidu.com/?cecilly/blog/item/e5?1b17d7aaf409d5a044df?67.html

** 世界知名IT咨询公司薪情排行榜
世界知名IT咨询公司薪情排行榜

世界新五大IT咨询公司 IBM GBS（BCS），埃森哲，毕博，德勤，凯捷。从薪资水平上看，第一梯队：SAP、埃森哲；第二梯队：IBM GBS、HP咨询、毕博；第三梯队：凯捷、德勤 
1、SAP 

　　 业绩的大幅攀升直接带来了顾问和销售薪酬的提高，SAP今年从北大清华新招的刚毕业的硕士顾问基本工资起薪都在八千五（税前），一年十四个月工资。如果进入项目，享受每天 四百人民币的补助。SAP在销售方面，如各个行业的总监、高级售前顾问一般月薪在两万（ 税后）左右，加上年终各种奖励，普遍收入水平均在四十万左右。普通的销售一般年收入在二十万左右。咨询方面，项目经理年薪在三十万左右，月薪在两万左右。一般顾问年薪在二十万左右，月薪在一万五左右。SAP还在上海大连等地建立了研究院和支持中心，这些部门的待遇一般较低，普通的开发人员，如果不担任项目经理的话一般待遇在十万元年薪左右（主要拿固定工资，奖金很少）。 

　　2、ORACLE中国 

　　 2004年业绩整体不佳，本人了解很多sails都没有完成业绩，人员流动性也比较大。所以说 

　　大部分销售主要吃的是底薪，真正能拿到commssion的不多。ORACLE的行业销售经理月薪固定工资是一万五到两万之间，行业销售总监在三万左右，国内ORACLE从事application产品的销售大概有三十多人。顾问方面，ORACLE一般不自己做项目，因此oracle自身的顾问很少，主要是少量的行业专家顾问。这些专家的年收入一般在四十万左右。 

　　3、IBM BCS 

　　 IBM BCS中国区顾问大概不到二百人（包括管理咨询方面的顾问），销售团队大概约三十人 左右。IBM BCS整体业绩不错，但整个亚太区业绩一般。IBM BCS新招聘的硕士毕业进入公 司一般是band 6，起薪在八千左右，一年十四个月工资，同时，可享受各种项目奖金，主 要跟业绩挂沟。高级项目经理和咨询顾问年收入在四十万左右（band 8 or band band 9），普通顾问年收入在二十万左右。 

　　4、bearingpoint(毕博）  http://www.bearingpoint.com

    毕博现在的中国区咨询业务整合进了戴尔的服务里了：http://content.dell.com/cn/zh/enterprise/d/campaigns/landing-dell-consulting

　　 2004年亦取得不错业绩的一家咨询公司，实施项目包括石家庄制 药 中海油田中国石油东方石油勘探设计院等单位。Oracle实施顾问基本公司一万四到一万六之间，项目经理在两万五到三万之间。每天补助300rmb，各种项目奖金据说较少。以上是毕博咨询顾问部门的待遇，但其在上海和大连从事外包的公司一般待遇相对较低，同样职位一般低四到五千左右，如：毕博在上海张江的cdc部门从事oracle二次开发人员的待遇，一般月薪在六千到八千左右，除了每年十三个月工资外，其他没有任何额外收入。 

　　5、accenture 埃森哲 

　　 2004年亦得到了快速的发展，在银行 制造业能源电力行业都取得了不错的业绩突破，中国区顾问约有一百多人（不含大连从事外包的0机构）。埃森哲今年也在清华等高校也进行了校园招聘，硕士起薪在六千五左右。艾森哲整体工资水平较高，在五大中属于较高的水平。咨询顾问年收入一般在二十万左右，项目经理在三十到四十万左右，总监在五十到百万年薪不等。 

　　6、HP consulting 惠普咨询 

　　 2004年收购汉思后,中国区业务得到了迅速发展,首钢等一批超大型的项目的实施使公司收入得到迅速增长,另外,HP还在金融 保险航运等多个行业发力,从IT规划到硬件网络设计,客户群包括了:中国人寿 中远 中外运交通银行等大型客户.惠普目前SAP和ORACLE实施顾问主要来自于原顾问团队和汉普等公司.HP的待遇水平目前基本上和五大在同一等级.HP每年是十六个月工资. 

　　7、凯捷安永 

　　 五大咨询公司中最为低落的一家,2004年预计没有任何大项目进帐,顾问流失也严重,虽然其 目标行业定位于金融 保险高科技,但在细分市场竞争中IBM ACCENTURE BEARINGPOIT相比 ,竞争优势明显不足.公司待遇相对较低,副总待遇约为年薪十五万,作为实施顾问的待遇可想而知了。 

　　8、汉普 

　　 2004年联想将其业务打包转给亚信后,业务没有很大的起色.目前,汉普ORACLE团队大概有二十多人,SAP团队有五十多人,销售有二十多人,加上行政后勤人员三十多人,整个公司人员相比辉煌时期的2002年不可同日而语,次汉普非彼汉普,2004年汉在内部管理做的一件很大动 作就是降低员工工资,以前汉动辄年薪三四十万的老顾问被降低工资后,由于对待遇不满纷纷辞职而去,这包括业界为为知名的金** 郑**等人.现在汉ORACLE项目经验较丰富的实施顾问基本月薪在一万左右,实施项目期间每天150的补助,每月正常收入在一万一二左右,汉奖金很少,正常顾问收入在年十五万左右.SAP略高. 

　　9、汉得 

　　 2004年整体业绩有所下降,汉得目前员工数较多,目前是SAP和ORACLE的主要合作伙伴.汉得待遇相对较低,ORACLE顾问起薪在六千RMB左右,在项目上和不在项目上的差异较大,基本上在项目上的收入是不在项目上的收入的一倍. 

　　10、科森 

　　 ORACLE的主要实施公司,年营业额在两千万左右,目前有四个CASE在做,外包业务做的也不错.广东发展银行是科森目前做的一个较大的项目.科森的待遇在ORACLE实施方面基本上是行业平均水平. 

　　11、高维信诚 

　　 SAP号称实施ALL-in-one产品的最大一家公司,2004年虽然SAP比较火爆,但高唯的业务确有了下降,特别是有几个项目做砸了之后,影响十分不好,高维所投资的短信宝因为没做起来, 

　　一直处于亏损,给公司造成了很大压力,个别股东和高层分分跳槽而去.高维SAP实施顾问(一 

　　般)基本工资在六千左右,在项目上有一万多,高维实施项目顾问的津贴是不按天计算,统一 

　　按项目的回款来提成. 

　　12、德勤eloitte 

　　 五大咨询公司中最为末落的一家,主要是SAP的合作伙伴,虽然号称拿了不少单子,但单子回 款状况极差,更有被客户赶出门的业内笑话.实施的一家汽车制造厂经过两年至今还没有完全上线, 项目回款差造成了顾问流失危机,大批顾问纷纷转投IBM AC BP等公司,德勤目前 S AP团队大约不到十人,主要以新手为主.声称的顾问相当部分来自于香港德勤,非大陆人士. 

　　德勤SAP实施顾问一般月收入在一万二到一万五之间,项目经理在此基础上上浮50%. 

　　13、大唐兴竹 

　　 ORACLE电力行业合作伙伴,顾问年收入低于科森 汉普等公司. 

　　14、佳都国际 

　　 ORACLE曾经较推崇的合作伙伴,目前音信不多,公司位于广州,主要市场在南中国区. 


源地址：http://blog.renren.com/GetEntry.do?id=745949740&owner=250098065

** 管理咨询公司排名―战略咨询类10强排行
#+BEGIN_VERSE
   　1．麦肯锡管理咨询公司
　　　　全球最著名的管理咨询公司之一，1926年在美国成立，是专门为企业高层管理人员服务的国际性公司，在全球44个国家和地区开设了84个分公司，目前拥有9000多名咨询人员，分别来自78个国家，均具有世界著名学府的高等学位。其业务主要是提供战略方面的咨询，同时还涉足企业金融、商业技术和运营等一系列广泛的咨询领域及管理议题。麦肯锡中国公司被评为“中国最受尊敬企业”之一。
　　　　2．西杰优盛管理咨询公司
　　　　西杰优盛一直致力于企业战略咨询及相关管理咨询。经过多年的管理咨询实践，西杰优盛的业务横跨汽车、地产、文化创意、能源、电子等二十多个行业，具有领先的行业咨询经验，已成为国内最可信赖的战略咨询机构。西杰优盛优异的服务给客户带来了巨大的变化！几乎所有的客户在咨询成果实施后都不同程度获得了业务增长，实现了既定的发展目标，其中80%以上的客户业务在咨询结束后两年时间内，营业收入增长率达到了50%以上。
　　　　3．埃森哲管理咨询公司
　　　　全球领先的管理及信息技术咨询机构，2003财政年度纯收入达118亿美元。拥有83，000多名员工，在全球47个国家和地区设有110多家分支机构。为各行各业的客户提供广博精深的专业服务和业务解决方案。在公司战略目标的指导下，为了全方位地满足客户的需求，正在不断拓展业务服务网络，包括管理咨询、信息技术、经营外包、企业联盟和风险投资。
　　　　4.北京仁达方略管理咨询有限公司
　　　　仁达方略管理咨询公司是国内领先的大型管理研究与咨询机构，集团管理权威。公司拥有丰富的大型企业咨询经验，已成功为诸多行业旗舰型企业提供了全方位、高质量的组织变革咨询服务。公司创建了诸多引领性的先进管理理论与方法论，并推进在中国管理实践的运用。仁达方略通过全程跟踪的贴近式服务，帮助遍及国内重点行业的旗舰型企业和快速成长的优秀企业，如国家电网、中国五矿、中国电子、蒙牛乳业、大众汽车、晋煤集团、交通部海事局、金融街等，大幅提升企业的管理品质，实现与众多战略伙伴并肩成长。
　　　　5．毕博管理咨询公司
　　　　毕博（BearingPoint）-原毕马威管理咨询（KPMGConsulting），总部位于美国弗吉尼亚州麦克林市，是世界最大的管理咨询公司和系统集成商之一，拥有员工16000余人，年收入近29亿美元，服务全球2100多家企业客户，其中包括72家美国《财富》100强公司、318家《财富》1000强公司以及超过四分之一的环球《财富》2000强公司，并致力于服务中小型企业、政府机构和其它组织，是美国26家政府部门中21家的主要系统集成服务提供商。毕博（BearingPoint）有着极高的客户合作保持率，其中前150位的保持率为96％，而前50位大客户的保持率更是高达100％。
　　　　6.上海通和企业咨询有限公司
　　　　通和咨询是一家专业从事现代管理咨询服务的智力密集型企业，主要面向成长与变革中的中国企业，致力于为企业的战略转型、管理变革和资源整合提供系统性、科学性和实效性的解决方案，辅助客户全面提升竞争力。作为中国本土第一批专业化、职业化的管理咨询公司，经过多年不懈地探索和积累，依托成熟的咨询团队、丰富的职业经验、先进的服务方式、准确的市场定位，公司形成了自身独特的经营理念和运作模式，成为中国管理咨询业中最主要的机构之一。
　　　　7.鹰腾企业管理咨询有限公司
　　　　深圳市鹰腾企业管理咨询有限公司是YINTL下属的成员企业，公司总部位于坐落于深圳商务中心区，下设深圳、广州以及福建三个业务中心。鹰腾咨询秉承领先的管理理念，致力于为中国企业提供从战略制定、实鹰腾咨询标志施到绩效落地实施细节全方位的管理咨询服务。鹰腾咨询集多年的企业管理咨询实践经验，从战略管理、集团管控、流程优化与精细化管理、人力资本管理、企业文化建设五个不同领域进行了大量的研究、思考与探索，希望这些成果在服务客户、提升客户管理能力的同时，为客户创造价值。
　　　　8．天强管理顾问公司
　　　　天强管理顾问成立于1999年9月，成立以来天强管理顾问已经发展成为国内最具有成熟运作模式的管理咨询公司之一，长期以来致力于为本土企业提供专业化管理咨询服务，并坚持高起点、专业化、规范化的企业发展轨迹。天强管理顾问是上海市咨询业行业协会理事单位，曾连续多次蝉联“上海市信誉咨询机构”称号，曾荣获“中国最有影响力的百家咨询机构”，被新智囊等媒体评为“2007年管理咨询行业十佳”，曾入选全国最受客户尊敬的管理咨询公司。
　　　　9.佐佳国际咨询集团
　　　　佐佳国际咨询集团（Z.M.C）是具有全球专业化背景的管理咨询公司，自进入中国区开展管理咨询业务以来，凭借深厚的专业背景和卓越实效的咨询风格，成为令同行尊敬，客户满意的领先智业服务机构。佐佳以集团型企业战略执行变革为主要咨询专业方向，摒弃空洞的管控框架理论，整合平衡计分卡战略管理、集团管控模式、流程与组织变革、人力资源管理与企业文化体系设计等咨询模块，引领国际最新的管理理念与最佳实践，帮助中国企业集团实现高效战略执行，确保企业战略落地，成就卓越绩效。
　　　　10.北京中圣国脉管理咨询公司
　　　　中圣国脉管理咨询公司是一家专业从事管理咨询和管理培训的机构。中
圣国脉立足于中西文化和管理思想交汇的新加坡，在中国北京设立运营总部以服
务中国企业。公司现有企业管理咨询事业部、企业管理培训事业部、企业文化管
理事业部、企业商学院管理事业部，下设企业文化研究和服务管理研究两个研究
所，在长沙、青岛、深圳等地设有多个业务代表处。同时在石家庄成立河北中圣
翔光管理咨询公司，专门负责河北市场的管理咨询、管理培训业务和中国营销总
监资格认证等项目的运营。

这个数据仅供参考，或许并不真实。

#+END_VERSE
** 2011中国管理咨询公司排名
#+BEGIN_VERSE
*2011中国管理咨询公司排名*


1 
麦肯锡咨询公司
2
罗兰贝格咨询公司
3
 IBM全球企业咨询服务部
4
科尔尼咨询公司
5
正略钧策咨询公司
6
 AMT咨询
7
埃森哲咨询公司
8
凯捷咨询公司
9
华夏基石咨询集团
10
爱维龙媒咨询集团
11
北大纵横咨询公司
12
翰威特咨询公司
13
波士顿咨询公司
14
盖洛普咨询公司
15
毕博管理咨询  
16
天元鸿鼎咨询集团
17
锡恩咨询公司
18 
和君创业咨询公司
19
理实国际咨询集团
20
北京市长城战略研究所
21
佐佑咨询公司
22
世纪纵横咨询公司
23
北京零点研究集团 
24
上海天强投资管理有限公司 
25
远讯咨询集团
26
美式咨询公司
27
北京信永方略管理咨询有限公司 
28
北京朴智管理咨询有限公司 
29
北京九略管理咨询有限公司 
30
新生代市场监测机构有限公司 
31
广东现代国际市场研究有限公司 
32
北京环亚市场研究社 
33
北方亚事资产评估有限公司 
34
深圳泛中（AMR）市场资讯公司 
35
北京博采企业形象研究中心 
36
广东大通市场研究有限公司 
37
北京铭略管理有限咨询公司 
38
北京赢思强投资咨询有限公司 
39
北京开卷图书市场研究所 
40
北京捷盟管理咨询有限公司
41
北京勺海市场研究公司 
42
北京中电力企业管理咨询有限公司 
43
雅兴市场研究公司 
44
北京汉鼎世纪咨询有限公司 
45
北京国富创新管理咨询有限公司 
46
深圳市深远企业顾问有限公司 
47 
北京求是联合管理咨询有限公司 
48
北京中企联企业管理咨询顾问有限公司 
49
东方市场研究 
50
北京中通网信息咨询有限公司 
51
北京多星管理咨询有限公司 
52
北京华通人市场信息有限责任公司 
53
北京嘉丰融通咨询有限公司 
54
 IDC（International Data Corporation） 
55
北京美兰德信息公司 
56
北京永达信工程造价咨询有限公司 
57
广州市致联市场研究有限公司 
58
北京成伟企业管理咨询有限公司 
59
北京西杰优盛管理咨询有限公司 
60
北京联合智业企业发展研究院 
61
北京中化企协管理咨询中心 
62
天津市智道管理科技咨询有限公司 
63
视野国际财务顾问(上海)有限公司 
64
北京博原慧达企业顾问有限公司 
65
上海通和企业咨询有限公司 
66
上海复济企业管理咨询有限公司 
67
北京神州旗舰市场调查研究公司 
68
深圳市绩效企业管理顾问有限公司 
69
上海万隆管理咨询有限公司

*中国管理咨询公司排名top20*
 1．麦肯锡
 　　全球最著名的管理咨询公司之一，1926年在美国成立，是专门为企业高层管理人员服务的国际性公司，在全球44个国家和地区开设了84个分公司，目前拥有9000多名咨询人员，分别来自78个国家，均具有世界著名学府的高等学位。其业务主要是提供战略方面的咨询，同时还涉足企业金融、商业技术和运营等一系列广泛的咨询领域及管理议题。麦肯锡中国公司被评为“中国最受尊敬企业”之一。
 2、罗兰.贝格 
 罗兰 贝格国际管理咨询公司于1967年在德国建立，现已成为欧洲最大的管理咨询公司之一，隶属于德意志银行集团，在全球26个国家和地区设有35个办事处。公司的咨询顾问来自全球近四十个国家。专长于为企业提供公司战略、重建、重组、市场营销、物流营运、企业兼并后联合及人力资源管理等咨询服务，帮助您解决在市场进入战略确定、中国营运模式的建立、合资企业重建与购并、全国销售网络控制及招聘与保留人才方面的问题。 


 3．埃森哲管理咨询公司
 　　全球领先的管理及信息技术咨询机构，2003财政年度纯收入达118亿美元。拥有83，000多名员工，在全球47个国家和地区设有110多家分支机构。为各行各业的客户提供广博精深的专业服务和业务解决方案。在公司战略目标的指导下，为了全方位地满足客户的需求，正在不断拓展业务服务网络，包括管理咨询、信息技术、经营外包、企业联盟和风险投资。



 4．正略钧策



 　　创立于1992年的正略钧策是中国成立时间最久、业务种类最全、员工人数最多、专业化程度最高、影响力最大的管理咨询公司之一，也是最早在北京、上海、广州三地设立全资公司的中国管理咨询公司之一。正略钧策作为中国大型综合性专业化管理咨询公司，业务范围涵盖战略咨询、营销咨询、人力资源咨询、运作信息化咨询、教育培训服务、投融资咨询、高级人才服务、企业文化咨询、**咨询、管理图书出版等。



 5．毕博
 　　毕博总部位于美国弗吉尼亚州麦克林市，是世界最大的管理咨询公司和系统集成商之一，拥有员工16000余人，年收入近29亿美元，服务全球2100多家企业客户，其中包括72家美国《财富》100强公司、318家《财富》1000强公司以及超过四分之一的环球《财富》2000强公司，并致力于服务中小型企业、ZF机构和其它组织，是美国26家ZF部门中21家的主要系统集成服务提供商。毕博有着极高的客户合作保持率，其中前150位的保持率为96％，而前50位大客户的保持率更是高达100％。



 6、科尔尼


 科尔尼创立于1926年，是全球领先的高价值管理咨询公司，分布在35个国家60多个城市，全世界拥有5000名员工，2002年收入为10.84亿美元。在所有主要行业都拥有广泛的能力、专门知识和经验，并且提供全方位的管理咨询服务，包括战略、组织、运营、商业技术解决方案、企业服务转型和高级猎头服务。 


 7、波士顿


 波士顿企业管理顾问公司（BCG）是全球著名的管理顾问公司，在战略管理咨询领域堪称业内翘楚，并为公认的先驱。集团创立于1963年，拥有超过2800位专业顾问，在世界主要城市设有58个办公室。公司的使命是帮助客户超过其竞争对手。其在世界各地的主要客户都是规模庞大的企业，其中也包括发展迅速、在本行业内不断开创新领域的中型公司。主要业务涉及消费品及零售业；工业品；能源与公用事业；医疗保健；高新科技；金融服务。 


 8．北大纵横
 　
 北大纵横管理咨询公司成立于1996年，是国内第一家按照公司法成立的管理咨询公司，也是由北京大学控股、北京大学光华管理学院兴办的按现代企业制度规范化运作的专业管理咨询公司。北大纵横目前已经发展成为年营业额近亿元、拥有国内外名校MBA、国内外大型企业中高层管理人员在内的两百多名正式顾问、九十多位项目经理的大型咨询企业。北大纵横管理咨询公司品牌也已经成为中国咨询行业的最知名品牌。



 9. 爱维龙媒



 爱维龙媒咨询集团是一家定位明确的智力服务机构，是“中国化集团管理专家”。做为管理咨询从业者，传播管理思想是其不可回避的使命与责任。当今中国管理咨询领域，更多是亦步亦趋地模仿西方管理模型与技术方法，无论是集团如何管控还是组织如何设计，咨询公司向企业传递的是“术、末、用”的知识体系，而非中国企业家真正需要的“道、本、体”的思想修炼。这是中国管理咨询行业的现实与无奈。爱维龙媒做为中国传统文化哲学思想的传播者，向中国古圣先贤学习管理智慧，是我们爱维龙媒人的使命与服务定位。



 10．华夏基石



 　 华夏基石管理咨询集团由中国管理咨询开拓者彭剑锋教授创办，现已成为中国本土最大管理咨询集团之一，是中国企业联合会管理咨询委员会副主任委员单位。华夏基石秉承“为客户创造价值，与客户共同成长”的理念，推动近千家大中型中国企业进行战略转型、组织变革、机制创新、文化重塑。



 11．翰威特


 翰威特是全球最大的综合性人力资源管理咨询公司之一，具有60年的客户服务经验和市场先导地位，专长于为企业提供策略性的人力资源管理解决方案，其客户包括《财富500》中75%以上的公司。2001年度全球的营业额为15亿美元，于全球三十七个城市当中，共设有八十五个办事处，全球有一万二千多名顾问人员，总公司设于美国伊利洛州的林肯林郡。在大中华区，翰威特是目前规模最大、资历最深的跨国咨询公司。 


 12.美世咨询


 美世人力资源咨询公司是全球最大的员工福利、薪酬和人力资源管理咨询公司。2001年，伟世咨询全球营业收入约为17亿美元，2002年，"伟世咨询"在全球同步更名为"美世咨询"，业务遍及全球40个国家和地区，拥有142个分支机构及13,000余名员工为中国大陆的企业客户提供更多、更直接的人力资源解决方案与薪酬数据。 


 13.和君创业



 和君创业管理咨询有限公司是中国本土规模最大、实力最强、特色最绚的综合性管理咨询公司之一。公司由一流专家学者领衔创建,秉持五种系统咨询能力，为中国企业提供基于战略的资本运作与管理改进方案，推动中国企业的战略转型和管理升级。公司已经在企业文化、公司战略、组织设计、人力资源、运营管理、市场营销、资本运作、并购重组、私募融资、证券投资、基金直投等诸多领域形成了自己独特的服务能力与核心优势，为各行业大中型企业提供高水准的管理咨询与投行咨询服务，创造出众多堪称经典的杰出案例。



 14.理实国际咨询集团



 理实国际咨询集团是一家具有国际化背景的综合咨询机构，总部设在加拿大，拥有覆盖北美和欧洲多个国家的专家资源网络。在中国，理实国际奉行“国际水准、本土服务”基本准则，与具有国际一流的管理与咨询经验的资深专家一起，结合中国咨询与管理实践，为500多家国内外客户提供过管理功能咨询，并以优秀的服务品质赢得了客户、咨询协会以及全球合作伙伴的高度评价，曾经获得中国Top10金牌管理咨询公司称号，“优秀咨询公司奖”、以及“管理变革年度最佳咨询公司”和“中国咨询业十大领导品牌”等奖项。


 15.和君咨询


 和君咨询于2000年春在北京成立，是中国本土规模最大的综合性咨询公司之一，荣获北京管理咨询公司综合实力排名第一、中国咨询业第一品牌等称号,和君咨询集团的基本业务结构是：和君咨询＋和君资本+和君商学院.


 16.锡恩


 锡恩公司是专注于企业战略及战略实施的专业化管理顾问公司。提供的服务有战略绩效考核、企业社会责任系统、企业文化系统、常年顾问战略实施系统(运营管理)、集团管控体系、战略规划。由著名咨询专家姜汝祥博士创办。 


 17.天元鸿鼎



 天元鸿鼎咨询集团专注于企业发展战略规划、企业文化建设、人力资源管理、财务管理、项目管理等多方面的管理研究。专业团队汇聚了来自北大、清华等一大批国家级知名学府的专家，广纳本土高端、具备实战经验的管理大师，为企业提供优质的企业管理升级服务。

 本文来自: 人大经济论坛 管理信息系统 版，详细出处参考：
 http://www.pinggu.org/bbs/viewth ... &from^^uid=990981

*中国10大本土管理咨询公司*


 1．正略钧策管理咨询
 　　创立于1992年的正略钧策是中国成立时间最久、业务种类最全、员工人数最多、专业化程度最高、影响力最大的管理咨询公司之一，也是最早在北京、上海、广州三地设立全资公司的中国管理咨询公司之一。正略钧策作为中国大型综合性专业化管理咨询公司，业务范围涵盖战略咨询、营销咨询、人力资源咨询、运作信息化咨询、教育培训服务、投融资咨询、高级人才服务、企业文化咨询、**咨询、管理图书出版等。



 2．北大纵横管理咨询
 　　北大纵横管理咨询公司成立于1996年，是国内第一家按照公司法成立的管理咨询公司，也是由北京大学控股、北京大学光华管理学院兴办的按现代企业制度规范化运作的专业管理咨询公司。北大纵横目前已经发展成为年营业额近亿元、拥有国内外名校MBA、国内外大型企业中高层管理人员在内的两百多名正式顾问、九十多位项目经理的大型咨询企业。北大纵横管理咨询公司品牌也已经成为中国咨询行业的最知名品牌。



 3．华夏基石咨询集团



 　华夏基石管理咨询集团由中国管理咨询开拓者彭剑锋教授创办，现已成为中国本土最大管理咨询集团之一，是中国企业联合会管理咨询委员会副主任委员单位。华夏基石秉承“为客户创造价值，与客户共同成长”的理念，推动近千家大中型中国企业进行战略转型、组织变革、机制创新、文化重塑。
 4.爱维龙媒咨询集团



 爱维龙媒咨询集团是一家定位明确的智力服务机构，是“中国化集团管理专家”。做为管理咨询从业者，传播管理思想是其不可回避的使命与责任。当今中国管理咨询领域，更多是亦步亦趋地模仿西方管理模型与技术方法，无论是集团如何管控还是组织如何设计，咨询公司向企业传递的是“术、末、用”的知识体系，而非中国企业家真正需要的“道、本、体”的思想修炼。这是中国管理咨询行业的现实与无奈。爱维龙媒做为中国传统文化哲学思想的传播者，向中国古圣先贤学习管理智慧，是我们爱维龙媒人的使命与服务定位。



 5.和君创业咨询公司



 和君创业管理咨询有限公司是中国本土规模最大、实力最强、特色最绚的综合性管理咨询公司之一。公司由一流专家学者领衔创建,秉持五种系统咨询能力，为中国企业提供基于战略的资本运作与管理改进方案，推动中国企业的战略转型和管理升级。公司已经在企业文化、公司战略、组织设计、人力资源、运营管理、市场营销、资本运作、并购重组、私募融资、证券投资、基金直投等诸多领域形成了自己独特的服务能力与核心优势，为各行业大中型企业提供高水准的管理咨询与投行咨询服务，创造出众多堪称经典的杰出案例。



 6.理实国际咨询集团



 理实国际咨询集团是一家具有国际化背景的综合咨询机构，总部设在加拿大，拥有覆盖北美和欧洲多个国家的专家资源网络。在中国，理实国际奉行“国际水准、本土服务”基本准则，与具有国际一流的管理与咨询经验的资深专家一起，结合中国咨询与管理实践，为500多家国内外客户提供过管理功能咨询，并以优秀的服务品质赢得了客户、咨询协会以及全球合作伙伴的高度评价，曾经获得中国Top10金牌管理咨询公司称号，“优秀咨询公司奖”、以及“管理变革年度最佳咨询公司”和“中国咨询业十大领导品牌”等奖项。


 7.和君咨询


 和君咨询于2000年春在北京成立，是中国本土规模最大的综合性咨询公司之一，荣获北京管理咨询公司综合实力排名第一、中国咨询业第一品牌等称号,和君咨询集团的基本业务结构是：和君咨询＋和君资本+和君商学院.


 8.世纪纵横



    中国企业联合会管理咨询副主任委员，第二代咨询的领先者,拥有亚太十大咨询师、中国十大杰出咨询师领衔，中国企业家协会评选“十大咨询机构”和“十大值得尊敬的咨询专家”。我们服务过的国有企业有中石化，中石油，中航一集团，中央电视台，中粮集团，北车集团，大庆集团，伊利集团，鞍钢集团，重庆啤酒集团等，我们服务过的民营企业有雅戈尔集团，横店集团，鲁能集团，华立集团，奥康集团，精工集团等。



 9.佐佳国际咨询集团
 　　佐佳国际咨询集团（Z.M.C）是具有全球专业化背景的管理咨询公司，自进入中国区开展管理咨询业务以来，凭借深厚的专业背景和卓越实效的咨询风格，成为令同行尊敬，客户满意的领先智业服务机构。佐佳以集团型企业战略执行变革为主要咨询专业方向，摒弃空洞的管控框架理论，整合平衡计分卡战略管理、集团管控模式、流程与组织变革、人力资源管理与企业文化体系设计等咨询模块，引领国际最新的管理理念与最佳实践，帮助中国企业集团实现高效战略执行，确保企业战略落地，成就卓越绩效。



 10．西杰优盛管理咨询公司
 　　西杰优盛一直致力于企业战略咨询及相关管理咨询。经过多年的管理咨询实践，西杰优盛的业务横跨汽车、地产、文化创意、能源、电子等二十多个行业，具有领先的行业咨询经验，已成为国内最可信赖的战略咨询机构。西杰优盛优异的服务给客户带来了巨大的变化！几乎所有的客户在咨询成果实施后都不同程度获得了业务增长，实现了既定的发展目标，其中80%以上的客户业务在咨询结束后两年时间内，营业收入增长率达到了50%以上。


 本文来自: 人大经济论坛 管理信息系统 版，详细出处参考：
 http://www.pinggu.org/bbs/viewth ... &from^^uid=990981


#+END_VERSE
* 管理咨询
** 要动态经营不要战略规划
http://www.amt.com.cn/html/ManageFront/AMTPoint/2013/0125/1090.html

** 主动管理，核心人才管理的新修炼
   什么是核心人才?

提到核心人才，不同规模、不同行业、处于不同发展阶段的企业会有不同的界定，但通常会包括这些要求：根据岗位价值评估，所在岗位在企业里岗位价值较高，属于比较重要的岗位；能够胜任岗位的需要，业绩表现在良好水平以上；拥有企业发展所需要的关键能力，在某一专业领域里具有较高的专业水准；在人才市场上比较稀缺等。一般，核心人才通常是企业内部占20%左右、影响企业80%左右绩效的人才。

     核心人才流失问题是国内企业人力资源管理关注的重点

核心人才的流失，一直是各个企业关注的问题：核心人才通常需要较长时间的培养，或者是企业花了较大的成本从外部招聘来的；如果主动流失了，会对企业的经营带来较大的负面影响，如果去到了竞争对手那里更会对企业的经营造成伤害。

核心人才的主动流失原因主要有三种

（1）核心人才认为自己没有得到公平的回报。这里所谓的回报是多方面的,主要包括收入、尊重、发展机会、成长等。市场经济中，核心人才对企业的贡献如果得不到对等的回报，不仅他们自身会不答应，其他竞争对手也会乐意给予他们公平回报的机会。

（2）核心人才没有得到满意的发展环境。核心人才，不仅需要企业领导的认同、支持和爱护，更需要有一个开放、包容、善意、规则透明、文化健康的内部环境。当企业内部环境对核心人才不够包容、不够开放、不够善意时，核心人才在企业里往往难以生存；当企业没有一个好的机制，没有规范的管理时，核心人才的才能也比较难以发挥。

（3）核心人才的职业目标与企业的发展不匹配。企业有自己的使命、远景、价值观，核心人才也有自己的使命感、职业追求、价值观。核心人才无法认同企业的价值观，或者核心人才认为企业的远景实现无法达到自己的职业追求时，都会选择离开。

在核心人才的保留上，企业通常会采用九种措施

（1）法律留人：和核心人才签订竞业限制协议、商业秘密保护协议、主动离职补偿金等措施，为核心人才流向同行业企业、利益关联企业设置障碍；

（2）金手铐留人：通过股权、期权、分红权、购房购车无息贷款等措施来绑定核心人才的中长期服务，使核心人才离不开企业；

（3）回报留人：提供行业里有竞争力的薪酬福利，提供企业内部领先的收入水平，建立企业内部人员对核心人才的充分的尊重；

（4）发展留人：为核心人才提供定制化的职业发展规划，在发展机会、学习机会上向他们倾斜，保障他们职业的竞争力和专业水平的持续提升；

（5）感情留人：企业通过领导人的个人关怀，企业人力资源部门的人性化措施，企业对核心人才家庭的关怀等，使得核心人才对企业充满感情；

（6）事业留人：企业能够不断向前发展，并具有伟大、可实现的目标，能够给到核心人才向前前行的动力和激情。

（7）退出留人：为核心人才解决后顾之忧。包括：为核心人才退出提供各种形式的生活补助，保障核心人才未来生活的品质；核心人才退出后享受的荣誉员工身份和福利待遇，这有助于核心人才的心理满足和对企业的情感依存；核心人才退出后为服务企业继续建言和奉献的机会等等。

（8）文化留人：企业拥有优秀的企业文化，在经营哲学上具有深厚的底蕴，能够获得核心人才内心的认同。

（9）团队留人：企业具有高素质的员工，团队搭配合适，团队合作意识强，执行力强、工作效率高，便于核心人才取得事业上的成功。

国内企业对核心人才的管理分为三个阶段

从目前国内企业的实践来看，按照国内企业在核心人才的管理上所要解决的主要课题差异，可以大致分为三个阶段：

第一，核心人才保留阶段。大部分中小型企业基本上处于人才保留阶段，这些企业主要靠感情留人、事业留人，但由于和规模企业相比回报不高、发展不快、团队素质较低，面临着核心人才主动流失的风险和压力，外加上内部基本上没有形成供应机制和供应能力，只好把核心人才的保留当做核心人才管理的重点。

第二，核心人才培养阶段。对于具有一定规模、或者处于成长阶段的企业来说，相对于核心人才的保留，更看重核心人才的培养。企业在飞速发展，对核心人才的供应需求大，单靠外部供应满足不了需求，因此非常重视核心人才的内部培养，并把建立起核心人才的内部培养体系和健康的内部供应机制作为核心人才管理的重点。处于这个阶段的企业，在核心人才的保留上主要靠发展留人、事业留人、法律留人、团队留人等。

第三，核心人才主动管理阶段。对于一些优秀的规模企业来说，在核心人才的保留和核心人才的培养两个方面都做的比较好，企业现有核心人才、以及后备核心人才都很充足，这些企业在核心人才的管理上基本上处于主动管理阶段，会主动的请不适合的核心人才离开，并保持核心人才处于最佳年龄段。处于这个阶段的企业，在核心人才的保留上更多地靠金手铐留人、回报留人、退出留人、文化留人等措施。

为什么要提倡对核心人才的主动管理？

因为，核心人才是有职业生命的。再好的人才，作为企业核心人才的服务时间往往是有限的。以企业高管这种核心人才为例，相关调研显示，目前中国企业高管的平均年龄在47岁左右。国内某省的一份调查数据显示，民营企业总经理平均年龄在42岁左右，其中低于50岁的超过80%，低于40岁的达到40%以上。当人才成为企业的核心人才，自身各方面都达到了成熟，经验、年龄、专业能力都达到了一定的高度，可以为企业创造出较高的价值。但核心人才会老去，人才的巅峰状态会逐渐消退，核心人才的退出是必然的。就像足球运动员一样，足球明星们的黄金时间往往是有限度的，当巅峰不在的时候就是挂靴的时候。

如何才能做好对核心人才的主动管理呢？从管理实务上，应重视以下内容：首先，企业有完善的人才培养体系和有序的核心人才继承计划，解决企业核心人才的供应，这个目前国内很多企业已经重视起来了。其次，企业有完善、科学的人才退出机制，核心人才能够完美的谢幕，这个方面目前大多数企业都还不够重视。第三，企业能持续的做好核心岗位与核心人才的匹配，保证核心岗位上核心人才处于高绩效的工作状态，这个需要完善、科学的岗位管理、绩效管理，以及企业领导人的负责、重视和践行。

可以肯定，随着国内企业人力资源管理水平的不断提升，会有越来越多的企业在
做好核心人才的保留和培养两项重要工作的同时，主动的对核心人才进行管理，
以持续保持核心人才队伍的竞争力，使得企业的核心人才队伍成为企业的竞争力
的源泉。
http://www.adfaith.com/wzgd_detail/newsId=8c986a89-394c-41f0-ac8a-fe7c3e523352.html
* 生产性服务业
** 生产性服务业发展路径与对策
------以河北省为例
2012-5-4 16:07:31 来源：人民论坛中旬刊（总第362期） 作者：王 静 谷慧玲

　　【摘要】现代产业演进的规律表明，生产性服务业的快速发展对提升制造业核心竞争力具有重要影响。河北省作为资源型制造业大省，要强化优势产业支撑，提高产业核心竞争力，就必须突破生产性服务业发展相对滞后的瓶颈，加快发展生产性服务业。该文结合河北省实际情况，揭示了生产性服务业发展过程中所面临的种种问题，并提出相关建议。

　　【关键词】生产性服务业 问题 对策

　　加快生产性服务业发展，既是实现河北省经济结构战略调整、提升综合竞争力的客观要求，更是促进产业链向两端延伸，增强产业可持续发展能力，实现产业格局由“河北制造”向“河北服务”转变的必然选择。

　　生产性服务业的内涵

　　生产性服务业是指直接或间接为生产过程提供中间服务的服务性产业，它涉及信息收集、处理、交换、传递、管理等活动，本身并不向消费者提供直接的、独立的服务，而是为生产与商务活动提供服务。它是从制造业内部生产服务部门独立发展起来的新兴产业，依附于制造业企业而存在，贯穿于企业生产的上游、中游和下游诸环节，把日益专业化的人力资本和知识资本引进制造业，是二三产业加速融合的关键环节。

　　生产性服务业具有高科技含量、高附加值、高产业带动力、高成长性、低资源消耗、低环境污染等特征，其发达程度，已逐步成为衡量区域竞争力和现代化水平的重要标志之一。

　　面临的问题

　　“十一五”以来，河北省服务业发展迅速，对整体经济的快速增长起到了积极推动作用。但与经济发达地区相比，河北省生产性服务业的差距仍较为明显，存在许多问题。

　　总体供给水平偏低。 *服务经济国家的一个显著标志就是服务业占GDP比重达
到70%，生产性服务业占全部服务业比重达到70%* 尽管近年来河北省现代服务业总体呈上升发展态势，但生产性服务业总体比重偏低，发展能级不高。2009年，生产性服务业产值占地区生产总值的22.36%，与北京、上海等生产性服务业优势地区相比，存在差距。生产性服务业发展相对滞后，与工业化进程不能同步发展，难以满足河北省经济发展尤其是制造业发展的需要。

　　发展层次较低。尽管生产性服务业中一些新兴行业的兴起改善了行业内部结构，但总体上看，河北省生产性服务业仍以交通运输、仓储和邮政等传统行业为主，仍处于低层次结构水平。当前金融保险业发展速度虽然较快，但与京津地区的优势相比仍处于起步阶段。2009年全省R&D占GDP的比重仅为0.78%，科研投入指标低于全国平均水平1.7%，创新能力有待提高。一些具有高科技含量、高附加值、高产业带动力的生产性服务业，如信息、高技术、商务服务业等虽然得到较快发展，但总体上还难以满足制造业转型升级的需要，与产业转型升级的要求也不相适应。

　　市场开放性不足。河北省生产性服务业中大部分行业的市场化和产业化发展较慢。一些高技术、通信等福利型和垄断型行业，尚未进入市场，缺少竞争机制，尚未建立市场决定服务产品价格的机制，导致行业发展缺乏动力。社会化服务体系尚未完全形成，产前、产中、产后的专业化服务薄弱，抑制了服务的有效供给，限制消费者的选择，影响整个服务业的产业化进程。生产性服务行业对外开放程度较低，2009年全省服务业外商直接投资34758万美元，占全省的9.66%，其中生产性服务业所占比重仅为3.19%，远低于第二产业所占比重。

　　竞争能力不强。从目前情况看，河北省现代物流、研发设计、信息服务、商务服务等生产性服务业发展滞后，规模偏小;文化创意、动漫产业、服务外包等新兴服务业起步晚、发展慢，尚未形成竞争优势;服务业集聚区功能不完善，创新能力较差，竞争优势不突出;品牌知名度较弱，尚未形成规模化、网络化、品牌化经营，缺乏一批拥有自主知识产权和知名品牌、具有较强竞争力的龙头企业。

　　制约因素分析

　　行业管理体制亟需理顺。服务业门类繁多，每一行业的特点和发展规律都不尽相同，因此，需要对不同的门类进行细分，并针对不同的行业特点制定促进政策，才能更有利于不同行业的发展。长期以来，河北省对生产性服务业发展规律认识不足、引导不够，生产性服务业中的一些新兴行业普遍存在多头管理、交叉管理和无人管理等现象，资源未得到有效整合，行业发展水平低。

　　产业联动效应相对较弱。在生产性服务业具备一定发展水平的基础上，如何通过加强产业联动，使服务业内部结构优化升级与产业结构调整相适应，这将成为今后生产性服务业实现质的飞跃的关键。从目前发展来看，河北省真正意义上的生产性服务业规模仍然较小，而且总体仍处在前期投入引进阶段，缺乏具有行业引领作用的龙头企业，短期内较难适应经济快速发展和资源优化整合的需要。

　　人力资源匮乏。生产性服务业具有高人力资本含量、高技术含量和高附加值的特点，其发展需要高素质的人才。一些新兴行业，如现代物流、电子商务、信息服务业、商务服务业等对创新人才、技术、技能型人才和管理人才需求迫切。尽管河北省积极引进人才，一些院校也调整方向，加大培养力度，但短期内生产性服务业从业人员的素质还远不能适应其快速发展的需要。

　　发展空间受到抑制。河北地处华北中心、京津两市的外围，受京津等相邻经济区域经济覆盖的影响，其生产性服务业对周围区域的辐射能力受到很大的限制。由于生产性服务业聚集性和规模性的特点，河北省不可避免地要面对京津等相邻区域的竞争，其发展生产性服务业的人流、物流、信息流、资金流都会受到不同程度影响，这在一定程度上制约了河北省生产性服务业的发展。

　　发展路径与对策

　　加强引导，提供政策支持。要从战略的高度重视生产性服务业的发展，根据总体规划和土地利用规划，支持生产性服务业实现区域性集聚，以产业集群的模式发展河北生产性服务业。运用法律、行政和市场相结合的手段，引导资源要素向生产性服务业重点领域和区域集中。引导民资、外资参与生产性服务业企业的改组改造，鼓励和支持各种分散的、弱小的、不同所有制的生产性服务企业进行重组。对生产性服务业的重点建设项目、关键领域和新型行业要给予诸如小额贷款、财政贴息、适当降低资本金比例、多渠道增加投入等政策扶持。

　　加快主辅分离，实现联动发展。长期以来，河北省企业“小而全”、“大而全”现象比较普遍，企业负担过重，影响其效率提高。要加快主辅分离，选择引导一批生产规模较大，条件较好的企业率先分离服务业，从企业分离出来的服务项目要进入市场，分离出来的服务企业要参与市场竞争。通过制造业服务剥离一方面可使制造企业集中力量抓关键环节，提升核心竞争力，实现转型升级;另一方面剥离后也会形成专业化的生产性服务企业群，提高生产性服务业企业的水平和规模，为制造业提供更好的专业性服务，构建生产性服务业与工业互动发展的新机制。

　　加强人才培养，实施人才战略。生产性服务业作为知识密集型产业，对从业人员要求较高。要牢固树立人力资本是生产性服务业发展的“第一资源”的观念，在吸引人才、使用人才、培养人才等方面要有新思路、新机制、新条件。营造良好环境，大力引进高层次、高技能、高素质的各类紧缺人才，重点引进通晓国际规则和熟悉现代管理的专业人才和领军人才。充分发挥高校教育优势，加快生产性服务业相关学科的建设，增设紧缺专业，为生产性服务企业培养合格的一线人才。同时，也要积极引导生产性服务企业，加大对人力资本的投入，加强对员工的培训。

　　扩大合作开放，实现资源共享。加强区域合作，重点搞好与京津生产性服务业的对接，积极引进京津的优质生产要素、名牌企业，借鉴先进的管理方式、经营理念和发展模式。加强与周边省份分工协作，推动文化旅游资源、交通运输体系的共同开发建设，发展一体化的现代物流体系。同时，主动承接国际服务业的转移，加快科技、信息、物流、金融、商务等领域的对外开放，大力促进国际生产性服务企业进入河北，吸引跨国公司将采购、营销等分支机构落户河北，重点引进高知识含量、高技术密集度和高附加值的技术服务、信息服务、金融服务、法律服务、国际商务服务项目。支持有条件的生产性服务企业“走出去”，使生产性服务业获得更大的发展空间。

　　实施品牌服务战略，提升竞争力。要加快培育服务业品牌和龙头企业，实行典型引路，以点带面。大力实施品牌战略，有计划、有组织的大力宣传生产性服务业重点企业和产品，对取得服务业名牌称号的企业加大政策奖励和支持，不断放大品牌效应。要围绕优势行业，选择有发展潜力、管理理念新、规模和业绩排名靠前的生产性服务企业给予必要的政策扶持，不断增强其核心竞争力。围绕重点发展的行业，继续加大重点项目的推进和扶持。在现代物流、研发设计、商务会展等领域，培育一批富有河北特色和国际竞争力的生产性服务业知名品牌，力争使河北生产性服务业在某些领域实现质的突破。

　　(作者单位：河北工程大学;本文系2011年度河北省社会科学发展研究课题《河北省生产性服务业发展路径与对策研究》研究成果，项目编号：201104048)

注：本文为《人民论坛》杂志原创文章，网络转载请为作者署名并注明“来源：\\
《人民论坛》杂志”字样。书面转载请联系010-65363752或邮件至
rmlt@rmlt.com.cn。

http://www.rmlt.com.cn/qikan/2012-05-02/41309.html




